// Builds src/data/photos.generated.ts from the images in public/stays/<slug>/.
// Records each photo's size and a tiny blurred preview used while it loads.
// Run after adding, removing or reordering photos: `npm run photos`.
import { readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const root = path.resolve(import.meta.dirname, "..");
const staysDir = path.join(root, "public", "stays");
const outFile = path.join(root, "src", "data", "photos.generated.ts");

const slugs = (await readdir(staysDir, { withFileTypes: true }))
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort();

const manifest = {};

for (const slug of slugs) {
  const files = (await readdir(path.join(staysDir, slug)))
    .filter((file) => /\.(webp|jpe?g|png|avif)$/i.test(file))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

  manifest[slug] = await Promise.all(
    files.map(async (file) => {
      const filePath = path.join(staysDir, slug, file);
      const { width, height } = await sharp(filePath).metadata();
      const preview = await sharp(filePath)
        .resize(16)
        .webp({ quality: 40 })
        .toBuffer();
      return {
        src: `/stays/${slug}/${file}`,
        width,
        height,
        blurDataURL: `data:image/webp;base64,${preview.toString("base64")}`,
      };
    }),
  );
}

const body = `// Generated by scripts/generate-photos.mjs. Do not edit by hand.
import type { Photo } from "./types";

export const photosBySlug: Record<string, Photo[]> = ${JSON.stringify(manifest, null, 2)};
`;

await writeFile(outFile, body);
const total = Object.values(manifest).reduce((sum, list) => sum + list.length, 0);
console.log(`Wrote ${total} photos across ${slugs.length} stays to ${path.relative(root, outFile)}`);
