// Generated by scripts/generate-photos.mjs. Do not edit by hand.
import type { Photo } from "./types";

export const photosBySlug: Record<string, Photo[]> = {
  "ample-house": [
    {
      "src": "/stays/ample-house/01.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAkAA4BaJbACdAEWvECPmugAAP5AumQX8/c9sU9Qs7+YoYQFo6qQ0b42U2rXA3bwcKPlIXk6g8mtsea1jHNdrRwJhuddkl/GQvEQFvzN1KWy7uJ8O672AAA="
    },
    {
      "src": "/stays/ample-house/02.webp",
      "width": 1700,
      "height": 957,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkAA4BaJQBOgCBrH9NQZQAA/ukpbF+Ny1ShMMmcQ30JUK8/NQNMFJNVPRZ+8/JdL7lp0ct+xYspddHMC0ZyWQAAAA=="
    },
    {
      "src": "/stays/ample-house/03.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwAgCdASoQAAkAA4BaJbACdAEQZIVz0seloADOOrrU4U/J0qF9g8AXWuJKSf1+8JXM98ZlJInXfCsUkFpZLbf69QddzRFdg3MABbag4EucXWOCLr6jHt1JM/P8Xtk8AAA="
    },
    {
      "src": "/stays/ample-house/04.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAkAA4BaJYwCdAEDu1cqlBzwAP7o9Ge+1YKqXgmrCAPLBqSyBrFUD1amvmRroiirLxGfsA6f2IRIivAzOhyXu5g6dUAA"
    },
    {
      "src": "/stays/ample-house/05.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAkAA4BaJQBOgMW+5FuxVJQAAPu962YJE+pzr5M6swILK6ioh3Y8rv4KXmO32GCuZDaI2pu7mN4isipyA4ibe/KaroAAAAA="
    },
    {
      "src": "/stays/ample-house/06.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAkAA4BaJYwCdAYtAsKZmADeTlhCBhgM535mU+Cwh74dPYg4FjCcNoAE4Uqz1Mu4mbV9lMWkKSbZya7WaYxE7m4EwO/xrErlAAAA"
    },
    {
      "src": "/stays/ample-house/07.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAkAA4BaJQBWABe3My31KgAA9VOO03/iXN7TTys9yuHLKeWo3xuhRtxusNfHZwP8LaLdXgY2b/9JBBOwAA=="
    },
    {
      "src": "/stays/ample-house/08.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAkAA4BaJYwCdAD7UqTq1gAA/sPycj+YttVhLjoTM0l8sKog8ZnsmiO0s+DiyIVRqU/6AbfmFvpIAAA="
    },
    {
      "src": "/stays/ample-house/09.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAkAA4BaJYgCdAYrdtQWwJ6AAP6tAF1ira4GVl4vE8V8VB2xteS7PVkr3/BQ+LYICUorjix451v68uk5B6hPJD0ysj/v/ngAAA=="
    },
    {
      "src": "/stays/ample-house/10.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAkAA4BaJbACdAEecJlHraQAAP678LXOsM5zQSDIavynzTAVUTTxKp+g1NV72RKeybH6rfUgfKskKJJ4i8N+XyeZF711t4AAAA=="
    },
    {
      "src": "/stays/ample-house/11.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoQAAkAA4BaJbACdAYv1yfCvL9jsADOMeU1lGJAvnMrIb7GbRjRnLCj3dLwY0vX5z1a7h/fHpOSaykdIzJxGu2SEr8lHVAn88mYbMNpWEyVAAAA"
    },
    {
      "src": "/stays/ample-house/12.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA4BaJZgCdADJwtsmbwAA/u0Ll16PPU15IcPOF/HUFLcCEn1yXkhCsaQVQ9lwdk7egQSg9nMkwkOApDl3bMo9r4KhoAA="
    },
    {
      "src": "/stays/ample-house/13.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoQAAkAA4BaJZwAAi96UfIAAP3Dvm8L06uaQQpf/meeq43wmUmKCI6O776NVXZcHsb8KiTM0YNatkS9KUnWLgAA"
    },
    {
      "src": "/stays/ample-house/14.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJQBdgBtuF1HoAAD+pqenvqhS/jc4dncfdBhaLC1skw/lCRcqDTzEHm6raR/I8aHLCOt8Cg+1G+dlmccdqgUSNMAAAA=="
    },
    {
      "src": "/stays/ample-house/15.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJYgCsAEDCzpsYAD+P0ww4NRNy2MJ3TTBU4DsDgPokah4mrVuZetKpGUvNijoros93T6Ts5t86HQ9LrB+cg4t3dgAAA=="
    },
    {
      "src": "/stays/ample-house/16.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAkAA4BaJYwAAp10OlXxQZwA/tK1fr+g/jB/cF2B08+/PJu+B33wL1tJOKGPn+qcfKiytQ0agTO5VnwAAA=="
    },
    {
      "src": "/stays/ample-house/17.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJYgCdACUhRL0wAD+OKQX5ycQ2DL/+hqBbA5KbJa9KrIt64XR0JwzjJ37UvVY25uV2oTvURMTxElBqRzJv6BQAAA="
    },
    {
      "src": "/stays/ample-house/18.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoQAAkAA4BaJYgAAlZMVciAAP7ur0PUWNLxTv8G0a/PhduTaNbeBoVJUy/qhHT2EbGb/GHsf8FwvyIPypDHayjjYHgAAA=="
    },
    {
      "src": "/stays/ample-house/19.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAkAA4BaJYwCdADD2/Ut4ADgEnsc0LPk+dU/YoJqPuDrJ5yMsqAlNFiUIhpMhvtBRSWvbAXwiJrNAHRArqRAAAA="
    },
    {
      "src": "/stays/ample-house/20.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAkAA4BaJQBOgCHq2SnPMpAA/tWtonTDBfjUKTwEip+49AoCxOTxHTMpKHI3hoHl7vX/Zo3pDqfw5r4AAA=="
    },
    {
      "src": "/stays/ample-house/21.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAQCdASoQAAkAA4BaJYgCdACTNG+wAP5ZcN8ySsjD2a5oDDJn2VCkhI8/+Wz61gcENhGHHScbGEx6MPjhx5mYh2ltZboWIxQ2OJXQAAA="
    },
    {
      "src": "/stays/ample-house/22.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAkAA4BaJQBOj+ADMOymMegAAPyO8ZPJsBWGw75bkL3jJj2Sn9/RbzF3aHy3IUXhl7MiRUM0Nx72PeJStoJ8igVpRvzZMgAAAA=="
    },
    {
      "src": "/stays/ample-house/23.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAkAA4BaJYwCdADw8Cv1YvgwAP7Ha1dbFUVsYARFdOagkxoin05LnJvWrGAWo8uvSCU+GbOb/o3sZhj/CmF2f+pgAAAA"
    },
    {
      "src": "/stays/ample-house/24.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAkAA4BaJQBOgBbdBlGdAAD94y0aqY9PABNjSuAt+iIsuV7cGhYzBP4TJT6jlkf6topk8t95Ru5c3z0FR3AAAAA="
    },
    {
      "src": "/stays/ample-house/25.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA4BaJQBOgBxvt2I1wgAA/q2xM1yEs1jE2CAaL9azyesM4dXAOq/SK6oYP1YM36NAh/EUZzAPFxTBQYXhYfLdJN3AAAA="
    },
    {
      "src": "/stays/ample-house/26.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACQAQCdASoQAAkAA4BaJQBOgBszoTAA+OTkKqQexnj+IfDw+eAeJ5Abuh8mZ5ENnaSyHbmq4x1QLkRXxGG3w2nt6RY2b4AfItYQAA=="
    },
    {
      "src": "/stays/ample-house/27.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAkAA4BaJYgAAvfARvunZPAA/phN4jeuyCDfEkV8wSmh48k/ef52+YiwY+MFmiOQFcrnh2oVuC8t5XKATVzno+N+8HbYlwAAAA=="
    },
    {
      "src": "/stays/ample-house/28.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAkAA4BaJQBOgCL2f5ja6AAA/qjl1CdBM303s8PVJdSjlT5FHN4bOoz4aY+jpXlChBr2GldOufHIpTwmH59Jcwr3GIWewih2tlAMAAA="
    },
    {
      "src": "/stays/ample-house/29.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJYgCdACUhRL0wAD+OKQX5ycQ2DL/+hqBbA5KbJa9KrIt64XR0JwzjJ37UvVY25uV2oTvURMTxElBqRzJv6BQAAA="
    },
    {
      "src": "/stays/ample-house/30.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoQAAkAA4BaJYgAAlZMVciAAP7ur0PUWNLxTv8G0a/PhduTaNbeBoVJUy/qhHT2EbGb/GHsf8FwvyIPypDHayjjYHgAAA=="
    },
    {
      "src": "/stays/ample-house/31.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkAA4BaJYwCxC8AFlLDVAAA/mWWoa4ak+01RhSVY9FWz5qzRpwl4J7lFccQ6dBJ5VZ4c5ODT5vrrJtLO3BvXWaAAA=="
    },
    {
      "src": "/stays/ample-house/32.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAkAA4BaJQBOgB08gc+bIAD8B8rH4s8lM5rA3blV/D/OqT5RrmZzS9fNvqKP2yvqvRwIvXWU3nuP5wAAAA=="
    },
    {
      "src": "/stays/ample-house/33.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoQAAkAA4BaJYgCdACPYEAAAPfULTyXQW9dtiGfvWR+GYb/zcvqkrqQl8LZL5kQEZzu+7mXiDYYlQghBTClDAAA"
    },
    {
      "src": "/stays/ample-house/34.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoQAAkAA4BaJQBOgBa+TqgAAP6psQhdrPEJuQPw2tJ4x0dEoA+v6RSG10V2ZXBqJ14uOGV/nRugX8zhMzwbCenGv1eAAA=="
    },
    {
      "src": "/stays/ample-house/35.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAkAA4BaJZgCdADp0NwuGAAA8UFymbq3bHUeiHFvfp8VeU9MKG0W4X8nd5bp/DWFcmZNcjoqelxatNrdZmtMGWg7kUAA"
    },
    {
      "src": "/stays/ample-house/36.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAkAA4BaJZQCdADdccvr9UAAzATTwXjIvan+KeTi3ePFshIDCBzxjFejs/5GQoFvE0BCxrlex6ZGydVmAA=="
    },
    {
      "src": "/stays/ample-house/37.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoQAAkAA4BaJYwCdAEW0voVDfgAzWfbRqTKIxYlJ+OwP9tflQcX4LrFKNlV4grmjcWwwYAA"
    },
    {
      "src": "/stays/ample-house/38.webp",
      "width": 1600,
      "height": 900,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoQAAkAA4BaJQBOgBY0wF7AAPzS0/PZaWmDABYK/DZuJkH+rDZBL1x5cSPb0ifRHMULSeIHw1pg0PvoAAA="
    }
  ],
  "boutique": [
    {
      "src": "/stays/boutique/01.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAACwAQCdASoQAAkAA4BaJagCdACArlyMAP62PvVgd/SL5xvvWx7jc3idT5S9JshdbA38fhkcDbzJfJxSc1DVBVuv2s9GZcVBqF7F1u7bu7t4cue6jXZDBp+XO7AAAA=="
    },
    {
      "src": "/stays/boutique/02.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAQCdASoQAAkAA4BaJYgCdADE/b4AAOIfe3K5wYzjOl/CJqTRyjW1jcFsZcRw/6GlHiTs1KKg1Lg5ongs6cmfs5qwVonoXwXvLNRLeQp0LAAA"
    },
    {
      "src": "/stays/boutique/03.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAQCdASoQAAkAA4BaJaACdADOj7oRAAD+HiU6s6jV0UIpXArLv8eMk5FK25M5CecKV1hvqfRt8X6XRKDtzwbA8HwmQQj6NuMhFThQV/Jq/bssmgRWSheqnjuiMAAA"
    },
    {
      "src": "/stays/boutique/04.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQAAkAA4BaJbACdAC3ZHt+gAD+gZWBTgKVO9ar/m6qLvyd/yAaxmYaDHU3oDeYIE8+GntUvVm4RAgtJs2Yn8Dfv+hctSKtAMHNTSp8A8DAAAAA"
    },
    {
      "src": "/stays/boutique/05.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAkAA4BaJZACdACq20Id6AD+0KM6QU3RtgPi+8oK6KumqHXHIFRXxF8PFS2Ma6EcyBYTagrYgadzRhiXqggoo2WKKdAA"
    },
    {
      "src": "/stays/boutique/06.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoQAAkAA4BaJZQC7AEfv3iHNIgA/M7R6EXAUlLrezQQXFO5SpT2kcQieojvYI3FhN9kyG8ZAAA="
    },
    {
      "src": "/stays/boutique/07.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAkAA4BaJZQAAn+5nZDzsAD4wGMASqcokujC9pxbPGsO6V57auyaACuZ7MNdlk8hkCWL3m7l4AAA"
    },
    {
      "src": "/stays/boutique/08.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoQAAkAA4BaJZQC7AEQPddaITAAAMsmuHZ50rgQvZ12aGeHNxY9XhFi2UK+wZ35qJGL+G57VwoUBZvFKrsYAA=="
    },
    {
      "src": "/stays/boutique/09.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAkAA4BaJZgC7AEVVhw4UAAA/uToigrhAWsYgLFLL9Twx5AdqFpoTWc4nSUBZItTe7Ub6FY5PWliM9F2KAAA"
    },
    {
      "src": "/stays/boutique/10.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoQAAkAA4BaJZQAAuaumt+wAPjIPo7k1UhpgSEwtRjWLwbYK2HD7vgoxizEx0xeQ196Vhk5aNDQnHb4Bh6UsAAA"
    },
    {
      "src": "/stays/boutique/11.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAQCdASoQAAkAA4BaJbACdADOahFu4AD+7dUav68NHwmdnK9dfHoRRbCmdiNW0clWRRB+Rvnu1xLdhQ5432sb/7KYQvOy3/Zgfx1JLj5OlP6ufKaON8LPAAA="
    },
    {
      "src": "/stays/boutique/12.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAkAA4BaJbACdADwhhlaY4YA8BydX2G53L+FRlI+xsr0Cb161980Epstm7OO9mHyHwjeRlx+Nz/0WCx6BkFO/XywOyhnNbzg1/10zQCUSRCX/QJwAA=="
    },
    {
      "src": "/stays/boutique/13.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACQAQCdASoQAAkAA4BaJbACdABV8gAA/vCHJIknrlXReGsSohp73RjtpsXAJX94kG4a+ZawYCt+DyPpOufqGyAJp4u5NyuqrHO6eiLjMK31LStOj1J7FpGKRoiVT/DVAAA="
    },
    {
      "src": "/stays/boutique/14.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAkAA4BaJQBOgBo6H2/MAAD+mA1NDy35dTMnxC59VbuUB6y7na5GPJz/RmkH7Kvk+maMEfxOusS/VdkfJy8AAAA="
    },
    {
      "src": "/stays/boutique/15.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACQAQCdASoQAAkAA4BaJZACdABoXJAA/Tb43vfE6OMwTIxt9ZMOxS8wagcZakcChziFt5+OjumJY0frV778rcFr1otfcFcWWDrAWAAA"
    },
    {
      "src": "/stays/boutique/16.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAkAA4BaJaACdAD7ABFCRtwA/qlV789UqvUXqzVlQ7ZIEFsdspzFTuyspjeUIDBK0EOsUxOGHkpcBx5rdguMoZ+6l0AA"
    },
    {
      "src": "/stays/boutique/17.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACQAQCdASoQAAkAA4BaJQBOgBGwtMAA9pktQpIwgO9rfXyaTGHnFP2KqqQwaTq3Jc7Ad1UeCMOTFbfuVo6J9gFgAAA="
    },
    {
      "src": "/stays/boutique/18.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACQAQCdASoQAAkAA4BaJYgCdACBqegAzje+R2QggWByNI/oGrUpa9okyAe2+WL7xPAj8f97UvdOMZgtWjRoNe/moSVs7pEWDWcZsHBHIAA="
    },
    {
      "src": "/stays/boutique/19.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACQAQCdASoQAAkAA4BaJaQAAo6nHAAA+GHIULRH80Y/BaoIbuWdOjCCMVByJP2rSS5TXy0Gza4AAA=="
    },
    {
      "src": "/stays/boutique/20.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACQAQCdASoQAAkAA4BaJZwAAeuN4cAA/rWP9d5Wyso2xn/CR3TZdMHu7ZeyNkRWc1jJ0Qqf/QWIZgAA"
    },
    {
      "src": "/stays/boutique/21.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAQCdASoQAAkAA4BaJYgCdAC3NixgAP63ZgdozUcfDDfE+8fBj3BkryIvHeSXRkIUqAGYMEle3FW/Gu3WNB8Vi6vKXrk16s+WUAAA"
    },
    {
      "src": "/stays/boutique/22.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAkAA4BaJYwCdADSGMON4ADOFZDKE80aUrMJ2A/tcx3UQ5N7838hQeWRegG59jSawex15c1QAAAA"
    },
    {
      "src": "/stays/boutique/23.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoQAAkAA4BaJYwAAtagmeQAAP7jUQLJb6b0rLrMQVofbU0nvB9+PsTEJx/b554FgqqFg1hfDQ078v9oAAA="
    },
    {
      "src": "/stays/boutique/24.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAkAA4BaJZQAAven+cCCVgAA/Oe104Is5mJ3xqjxPIquGV2HEMyFRYl/NKct982snZcNBPhSEVkHgAA="
    }
  ],
  "calm-boho": [
    {
      "src": "/stays/calm-boho/01.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAkAA4BaJbACdAED/P9UtvAA/rXo8p2J46S3N5d+D4forvB1/RH76bTS2eQuouuG2QA7WWfwOLF8c+KbgLEGZy8f98D69eVW5wb3KXdnaIdLjcAAAA=="
    },
    {
      "src": "/stays/calm-boho/02.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAkAA4BaJQBOj+ACOBDSw3IAAP2NPAG2YQ0NbS3ItYJH+Ef3Vi0euRCqe9Bg4u+HrVC/hAAFBeTy27p1mpFHabb6ROg9q9gfECUQAAA="
    },
    {
      "src": "/stays/calm-boho/03.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoQAAkAA4BaJQBOgBZzkp9YANvxee7jqVAk5/UuhRIs4PS78F8fSsbsyTu8/DhBmW/LJga/VlaliYAA"
    },
    {
      "src": "/stays/calm-boho/04.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAkAA4BaJQBOgCBsaGhy5JkAAP7ScYu44wXVXHBizxzcsbnyJ517+lVIi4Xa5tl6ZUb8ctj5n2ywxKAhhxHESoEtHdN1C4AAAA=="
    },
    {
      "src": "/stays/calm-boho/05.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJYwCdAC8I4KKgADNwv18tmM7OH6TQNjUq/V2gzv566rd7ZsYdmBpKlufI7lNTDyJQ6rivXzIhgoi7yTQAA=="
    },
    {
      "src": "/stays/calm-boho/06.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACQAQCdASoQAAkAA4BaJYgCdABoXJAA/sI+REuoDCxLBWQOrD57ScPHE69bmwCqyhGfXEGmhsCj7Aodd/Kjz66GmZLiCFqH8TWXEoE4AAA="
    },
    {
      "src": "/stays/calm-boho/07.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAkAA4BaJQBdgCDp/v167AD+0NsEveXI2YfxtZczxdKzj1Z5J9ulliks1A+na+xpYxNR2UELmBxHKsJ9bVAA"
    },
    {
      "src": "/stays/calm-boho/08.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoQAAkAA4BaJZQAAn/Fa6IYAPaN6GFTN4ScsXcRkkBHLoSE+5gGGRBGUGrqZ1Ly8pXSgymwqAA="
    },
    {
      "src": "/stays/calm-boho/09.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJZwC7ADbeuhbgAD42yqRy3IR+LQv34En2hR9Y2N0sHJ8VKcKvkIg9/OPe1fTaemleRJIwryWfLFiWfbAAA=="
    },
    {
      "src": "/stays/calm-boho/10.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJYwAApOjakhhgAD9eC+dmB+PSfFTjen+cDpqroJDyuqnPF2rYb2OZTqKdx2DGWmD9Lo0yQG3/tmD7v5MFI0eegAAAA=="
    },
    {
      "src": "/stays/calm-boho/11.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoQAAkAA4BaJQBOgButC6KOAAD+m3q6xD1gBm6HVwL2/FP48qVOyntvP4zYBOQhA+eNiV0Mbq756u7u5JbMaBKCCNxQwgmO2gWyNkIAAAA="
    },
    {
      "src": "/stays/calm-boho/12.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoQAAkAA4BaJYwCdADOBF6wAP6Uvs4d+GE4VVgFK3//1ifu1IgHxrnNp0lFdwogpMFdBG5Ika/c7bff77hy2AAA"
    },
    {
      "src": "/stays/calm-boho/13.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAkAA4BaJQBOgCPNhU/8iADhnEnpKKpn/XY53u7+t1/SessiIVpqf6ZXMGoAgPe02nXoscJRQmOz92PLoAAA"
    },
    {
      "src": "/stays/calm-boho/14.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoQAAkAA4BaJQBOgButC6KOAAD+m3q6xD1gBm6HVwL2/FP48qVOyntvP4zYBOQhA+eNiV0Mbq756u7u5JbMaBKCCNxQwgmO2gWyNkIAAAA="
    },
    {
      "src": "/stays/calm-boho/15.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAQCdASoQAAkAA4BaJQBOgBSmAPsAAPfQvNQM6mo9MKlXyO31BWgc1eGFr+rPrr4b+fSNN3JHIpm+spNlr9vSIwyB2AWAAAA="
    },
    {
      "src": "/stays/calm-boho/16.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAkAA4BaJQBOgBwu1thIAAD+3ae3nVFnS0hyq4cKQfRUcZc/Qm4JrdrPTsOixAWLIp3k/S67Hl0AAAA="
    },
    {
      "src": "/stays/calm-boho/17.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAkAA4BaJYgCdAD0Mcv6uAD86kZA7GncrlyU2PFVTtmcmHI0nDhl8c7iM0tBNaosmKuRpZUb0l0LXKv27AAA"
    },
    {
      "src": "/stays/calm-boho/18.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAkAA4BaJQBOgB/OoJwTEAD+l2bUxMZv9bKCpZm9j5fFRcmjTpfmSVU2sWwRYJoF/Q79DNStHqfaAAA="
    },
    {
      "src": "/stays/calm-boho/19.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAkAA4BaJaQAAuzX37jhYAAA/pmAbVbg88ahtAXp3RF+DfkClMrtRu9Cp1tKQI+arBdBf10FrIAA"
    },
    {
      "src": "/stays/calm-boho/20.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoQAAkAA4BaJaQAAi0HFV+GAADyjNg74umV50ktWbkXCn/Y3cL/9lWdwZS4IYgBphHYAAAA"
    },
    {
      "src": "/stays/calm-boho/21.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA4BaJZQCdAC90B8AiAAA+W1I+vep/EPJgDv1FaM04Buyo41Mk6zTHy6e5r+UysvoHUdsQEnwpn5OUxQ+OQf538zQgAA="
    },
    {
      "src": "/stays/calm-boho/22.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJYgCdACY+MprgAD0YN5lsK6Ogr4psimrr2knftSFg62MTAQzcnlmYQucLcKGjQX+nxoWsl3LemY3M/lvkE1EFASAAA=="
    },
    {
      "src": "/stays/calm-boho/23.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAkAA4BaJZQC7ACzy7fpgAD6nK0xNL7MAOlj+6Ta8Kra2H5zYzWmsMbP9gRhz01g+ZuVTW3mF5o6CKlXaPBgwAA="
    },
    {
      "src": "/stays/calm-boho/24.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA4BaJbACsAEQMtZhjgAA4gb1b7MLde16KnvIrjV+nxwdoats3o19U8kJGIeSyfvFpcOEoJUhUdYhHQWUn0kCFnbSAAA="
    },
    {
      "src": "/stays/calm-boho/25.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAkAA4BaJbAC7AEQAFGYUE0wAPqfQqnIrb1i//inSuijChO+0DmriUTTqaGSGBg4n/LJRLHLCwHso77poPCfTtzSwAAA"
    },
    {
      "src": "/stays/calm-boho/26.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAkAA4BaJZQCw7DMit2OrgAA/WmOWYXrHBEHLo+9Qt5DF0moHI+nxXu+Z4SJ4vgKewbQjWc/tVwAAAA="
    },
    {
      "src": "/stays/calm-boho/27.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoQAAkAA4BaJaQAAi0HFV+GAADyjNg74umV50ktWbkXCn/Y3cL/9lWdwZS4IYgBphHYAAAA"
    },
    {
      "src": "/stays/calm-boho/28.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoQAAkAA4BaJaQAAsZmcKAAAP7G1bTMVw6so3JwnzDoKa5jL6U86hUlWAgTzc2N94owAAAA"
    },
    {
      "src": "/stays/calm-boho/29.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACQAQCdASoQAAkAA4BaJZwAAemtCQAA/rXfPZUJ5eTgBuH16i0e1Pc3Q3b7Tx2GBlii1fD4sXY9x48RnKmv2j/SEAAAAA=="
    }
  ],
  "chillax-pod": [
    {
      "src": "/stays/chillax-pod/01.webp",
      "width": 1671,
      "height": 941,
      "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAQCdASoQAAkAA4BaJbACdAEK3yAcxgAA4k/Z7ZpECqdVUfKsHV5JdEkm/LFb/I3vqyBEpsHr/ZASANdkWKu3YWpwItax6tzmoOfIUKHvkfZOpNRjUJLk3zAATd8UAAA="
    },
    {
      "src": "/stays/chillax-pod/02.webp",
      "width": 2500,
      "height": 1408,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoQAAkAA4BaJQBOj+AQUROdag9WgAD+NG69TQrjNwbnd7U7Vbtjc2X2RBgpreHaCon1pzop7pwgXtVncYjDTSCSUVARgJ3NYDWFz/sAAAA="
    },
    {
      "src": "/stays/chillax-pod/03.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkAA4BaJZQCdAYs3FZSFoAA/kmWjjSR2sVYXaZMyPZR3ckBM4k5YQa5H0VHqetBqIiXaz7bhhXHwR031xBommoAAA=="
    },
    {
      "src": "/stays/chillax-pod/04.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAkAA4BaJQBOgB61ZziHJgAA9ynwImFI5/WVcjL6XxGYn5YhZ/5uQJ460KqskJuG9F5Vzhn2Y2TiyVVe/JuFwAA="
    },
    {
      "src": "/stays/chillax-pod/05.webp",
      "width": 2500,
      "height": 1408,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoQAAkAA4BaJQBOgBMsaEmwAP6F5xUDSkzOn1Vwkavsa2b2Jise9LifyTw8XznnTUjY2iDg1AaLzpZQHv08WU7u/FVrfkAenCCc8shgAAA="
    },
    {
      "src": "/stays/chillax-pod/06.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAQCdASoQAAkAA4BaJZACdADSLU5+2AD+1qyM4ZX1IGPb2XE5BaZWGp7GjAF5B/nBQQOAYo8uQSXb1Yku6e+w/CXZaSZzOj9+R8wqgf1aIlqXMabpUIvySAA="
    },
    {
      "src": "/stays/chillax-pod/07.webp",
      "width": 2500,
      "height": 1408,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAkAA4BaJZQCdACq2/GkcAD+mbbePgac/WgCLCNOqNyXypm9Ar7AXc07ie/M0ARb5ys2sDqtD7dO+E/MS4wtnOkN0wAA"
    },
    {
      "src": "/stays/chillax-pod/08.webp",
      "width": 2000,
      "height": 1126,
      "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAkAA4BaJZgCdAYvXaYt62nAAP61rU4THmgrvS+ZdEFnnGmG/j60+kK7LwqaRgWhdEQ/EABfWOQFIO8+hkZ72w8tv936126Eyg00+5Rto1AvjKAAAA=="
    },
    {
      "src": "/stays/chillax-pod/09.webp",
      "width": 2000,
      "height": 1126,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoQAAkAA4BaJQBOj+ABo+d8oAD+Gf7REgMZWixehaDvoDMka9eMLxJE5SNXvXUoUEOLjj6mYzuyPpMa6o0mqH3qEVys0nhTXzbCCJqAAAA="
    },
    {
      "src": "/stays/chillax-pod/10.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoQAAkAA4BaJQBOgA7vSO8AAPvsC+2NiDN8JTjTOcqx9uNptDrgb/WA42rNtI9kO81vM0AvJOd+pvXzn9s7uEN6Wwi2dFirVKwrEIxwAAA="
    },
    {
      "src": "/stays/chillax-pod/11.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAQCdASoQAAkAA4BaJYwCdACd+84AAP6EZv/GmoDr4mbBIBxmnvdfLljWnxxvQ73fhucU4P7Xf1RyZHne8zCcJX8jvPeoUAA="
    },
    {
      "src": "/stays/chillax-pod/12.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAkAA4BaJZQAD45OLiQTYlgAAPynbw8ulLgWI0g7bPVslh7Lg2oDwT9i5PmTj4zeoKzlvFGWRWs5dtqzJ5tCD5ZsyNlHcgh5GEKgAAA="
    },
    {
      "src": "/stays/chillax-pod/13.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABwAQCdASoQAAkAA4BaJQAAO/ukAAD+ZnYMGzsKK3sY5AU0PmSzT/23Z5+cf35qklXLee9GPNv9tYdzmDQ7O6H91EE+ByOdxHXAAA=="
    },
    {
      "src": "/stays/chillax-pod/14.webp",
      "width": 2000,
      "height": 1126,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoQAAkAA4BaJQBOgBocnRxAAPgjWJMeW+4hfA/5XpuyHEsuaz55FGNh72yfWgUPx74xQkmp1TUggHzhjtXoIAAA"
    },
    {
      "src": "/stays/chillax-pod/15.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJYwCdADBaVqcAAD+TNuxIGOg+Ub0gJTDwMMG0od+8ZZCqhWrkNLgDayQW6kF4zxfeOxdGgs2HZ3NvPEZPxyJXMwAAA=="
    }
  ],
  "comfy-pod": [
    {
      "src": "/stays/comfy-pod/01.webp",
      "width": 1600,
      "height": 902,
      "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADQAQCdASoQAAkAA4BaJbACdADl3P9nQADw3Rx5zKYGNnYgj6uSi+GjAXU5c7Fk0WkaVtd8Bd/lj+u4ltvV3Ui8IBHPtl3YwX7Z+SVxW0ksP80l5j6Dy3RP19MeKDz+sL5r13uJzGqn2bO2AAA="
    },
    {
      "src": "/stays/comfy-pod/02.webp",
      "width": 1671,
      "height": 941,
      "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAkAA4BaJbACdADpINKzCgAA/vBmx+laGxFaOaUGvh25+3ABaV4XMWdrzfMjE/4Aw8cuO318lRQ84S0wN8MsPGhIaZt6YO34Szg6O+hP7hV+384AAA=="
    },
    {
      "src": "/stays/comfy-pod/03.webp",
      "width": 1671,
      "height": 941,
      "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAQAgCdASoQAAkAA4BaJbACdADw7ipgf4IAAPwvCH/8IUabhQ+edxmSKK2p+CcF+mZdsgQpr88nqnhHJQlSQzb/ET9TuMY1XBYNv0rInxTUNlhSJHLeKi+FfRXnYFFnQnQgjxjEuVBl3HIfC1GA7D+AAAA="
    },
    {
      "src": "/stays/comfy-pod/04.webp",
      "width": 1670,
      "height": 941,
      "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAwAgCdASoQAAkAA4BaJbACdAD8Hbgkxq0UAAD+tljDgYiQKGwhGywdLd3SDhX1v8XrqD+PAQj0BcGfLwylCbHC8fWrgnc5X0t31BRLdaka5upoP+ZqP9omfJDebMX/zb+PRezPvzIz9bgAAAA="
    },
    {
      "src": "/stays/comfy-pod/05.webp",
      "width": 1671,
      "height": 941,
      "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQAgCdASoQAAkAA4BaJaACdAEDHu+bwjagAOJ/8aOZR7/Ng8sbuuHffhB0T0UXc83iRxeuX/f6tsWyuDd2oi0dE8mMSadVtrFtLhm8dS3ZLlYIxtltuqwsYJx788Z+o6F0PmG/8CVxLeQAAAA="
    },
    {
      "src": "/stays/comfy-pod/06.webp",
      "width": 1671,
      "height": 941,
      "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwAQCdASoQAAkAA4BaJbACdAC23/DGxBgA/tdh0wk5d2zyNM0+/4M1oqUCUlyFF276YI2HYk+rYW+1ExQRz609xKPfys4pHpLZH/UARiFyUtl/1xdhl2Iw1uUdbAOUMzViJpggrhwfUbLAAAA="
    },
    {
      "src": "/stays/comfy-pod/07.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoQAAkAA4BaJYwCdADC7XwwAP4Kw0/G13eHk0rdyk4eZ1eUx9CPvCC1woZvzFip7Y3V7j9hpYe6ZYvAAAA="
    },
    {
      "src": "/stays/comfy-pod/08.webp",
      "width": 1475,
      "height": 2620,
      "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAACwAwCdASoQABwALrV2u12jqampiYC0SgCo9EO+9m5niBgyxerGAAD5aEen9/SC7gYSQuT9Z/v4BILk2bFjc9pqGW2HmExRnwQtjLurCE3fAp4mIQWGi9/p0DOHGlHjNFJHz/nt3L6nglT6BQwJ+syJ8AA="
    }
  ],
  "dawn-stay": [
    {
      "src": "/stays/dawn-stay/01.webp",
      "width": 1200,
      "height": 706,
      "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADwAQCdASoQAAkAA4BaJbACdAYs3KFaEDIA/uFfEhVilx3gTL9etA4cCPvoxObazGQMXFJMQOeXcgh1cxUn2O+I0WpRx7lY+HY4BWBmtMIvwfPFrIq57L0oQBP2u7N3owpcrfQY6TM8D8ZuSrgAAA=="
    },
    {
      "src": "/stays/dawn-stay/02.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJQBOgBe+auXrAAD8c0hqvOoHIyNY9PXBABzxIYCEtEZBKbiSstDVFnNrBvH2McC0qlqgXFh5gYohKIpBufsBiXwAAA=="
    },
    {
      "src": "/stays/dawn-stay/03.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoQAAkAA4BaJZQAAgdCcZsAAP5U8I/SijVkUC/xHmbk8FFuU8W2DIhngTNWiuvDzhtplPrkC4VQ/pTRu6biKAAA"
    },
    {
      "src": "/stays/dawn-stay/04.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAkAA4BaJQBOgBVDXP3gAAD+r8RYXufHx1bj0N/nM3MDXzVdpbzk7KFDI4EQ9SgYtPbYGwBkHGY9kXSoAA=="
    },
    {
      "src": "/stays/dawn-stay/05.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAwAgCdASoQAAkAA4BaJZQCdAYtBt2OBZNZSAD+igvYbrwdsaEjnuvZMdmBM8NlpC7CgAHRgUcyG/DsgF5oK1JM/WF3a8LvYRVgEHNzJp5YbAAA"
    },
    {
      "src": "/stays/dawn-stay/06.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA4BaJYwC7ADdp0az7+gA/rAfras+7xYaSvQQhLh+HX0B3s9baAna4SvQDh1Tax6DeojWd5zkw8xxB9p/pdwduc2AAAA="
    },
    {
      "src": "/stays/dawn-stay/07.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAkAA4BaJYwCw7ClJ0b+4AD8+6AWrnl+E4NnTYI1ygsQ5DkZ/lm7Epl7OeERTEFcuuJFV0ZW39b2RanBAdFnz2OJHRirDB8RwOAA"
    },
    {
      "src": "/stays/dawn-stay/08.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAkAA4BaJYwAAv0jJYP3AAD0WyqPtt2K23GB7K0Dx8MEBJkKWl/DXsSCevoGrYOGPPCOPhBvEP9m/v4AAA=="
    },
    {
      "src": "/stays/dawn-stay/09.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoQAAkAA4BaJZwAAlg3svkBAADhfsXUMLKs3khuPKVYd0esIBNbaqqh4LUIEByWTvd2b4AA"
    },
    {
      "src": "/stays/dawn-stay/10.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAABwAQCdASoQAAkAA4BaJZQAAR0FgAD8x09eoh7sevkmYoyAjVNXKux6ropVx+knnmUT2tHcYEVcgEjgAAA="
    },
    {
      "src": "/stays/dawn-stay/11.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAkAA4BaJZwAAtteupHGgAD+wrSpbt7xNPN1lnkJnlmqrztOUHcKJrvTDOMTxq+LeYiJBOOdXZANSF5VqCgA"
    },
    {
      "src": "/stays/dawn-stay/12.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAkAA4BaJaAC/ODcov0ONwAA/u8nzlcn8ogAfBjyBBJM5MvzjBm8hM3/egvHFnQbkU5fsJQ5CTwJWx6z0+joAAA="
    },
    {
      "src": "/stays/dawn-stay/13.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoQAAkAA4BaJaQAAfa4lMYAAP6YEvIcBHUs3/EDlXXII3Lt+Yd2EQSpwy/+AAAA"
    },
    {
      "src": "/stays/dawn-stay/14.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACQAQCdASoQAAkAA4BaJZwAAUJn5WAA/fxeECaQpMWbMGv2xwSt9V8tandpFjh0empDYYjHlHX1T59U1w8JW39J1YQAAA=="
    },
    {
      "src": "/stays/dawn-stay/15.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAkAA4BaJaQAAmsM0DV2iADifRydRK3KWYlkAL5PhJ1hvV0DzSXAeePO5RyF34vpzdl/FCGw6UFAAAA="
    },
    {
      "src": "/stays/dawn-stay/16.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAkAA4BaJZwAAwF1YuwS12AA9q1FC2T4oRvaQPebsQTghXdf8feJQZd6qqfX1caxbp3v6bx29Xn+AAA="
    },
    {
      "src": "/stays/dawn-stay/17.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAkAA4BaJZQAAsSOEAz7hAAA/uzgX8qEoyi7XdRSpL8Wg5SnA6F9iUaVKQoZXi9f4VY9EqgB/gQA"
    },
    {
      "src": "/stays/dawn-stay/18.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAkAA4BaJZQCdIExEYvyLCgA4h4z+tbJ022IgdxVw+CIlg0gF6lq0K+gb7MwWEKobEd0GE6XKclmIKIkT+gA"
    },
    {
      "src": "/stays/dawn-stay/19.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAkAA4BaJYwCdADbquOIYAD+mTUqv77LIbmpbK3uWkSvQO6QZKJme6N2bOvxSwd7NcAN9ZfBshgA"
    }
  ],
  "jolly-house": [
    {
      "src": "/stays/jolly-house/01.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAkAA4BaJQBOgMW50BVNttAA/oo8NzE4ZN5aTe9QYTXoteQXL9zMIOf2Muk646mqPv7aEV2cbLbLuS2mf9IZi3Rxq46/J+j6Z/AA"
    },
    {
      "src": "/stays/jolly-house/02.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJQBOgB0+UEfCAAD+qeUyRJKQXKr7N6/jREuAhKiDRhtnSuGDeuhmI+3QmMyA6PtQ/bilOyQvnWkQX9smZdnAAAA="
    },
    {
      "src": "/stays/jolly-house/03.webp",
      "width": 1796,
      "height": 1011,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAQCdASoQAAkAA4BaJagCdADViegAAP48lld+yA4QIVHMmjTzBEn5IHyulVR4PfOPphq9u+gUV7V59PozJVbO5AyIFW7I35/0CAAA"
    },
    {
      "src": "/stays/jolly-house/04.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoQAAkAA4BaJZACdACkTowAAP5g6lWmqnWprS7m64DiJr5lyFY4oBZCoYhiPbMf55vNs+CMhKhyPK8GDCMNjdA1GAAAAA=="
    },
    {
      "src": "/stays/jolly-house/05.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAkAA4BaJQBOgBelmr9dAAD2vuGLA22COsWPG1p9gi6RiMjOQJfw+PhqNcVB+e4sXouay6LAPxPbdeDgxftzLxOJhiY0kjFfIjAA"
    },
    {
      "src": "/stays/jolly-house/06.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoQAAkAA4BaJbACdADveyrRQAD+6R1onT9IsG2P3xJp3/idrOr0iE98dEUL55V2DbED63nCtHkr4sXiYO+ku5dwU11z9xe33ANYptboAAA="
    },
    {
      "src": "/stays/jolly-house/07.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoQAAkAA4BaJbACdAYrdgf4/uaoAP7BqFaybD65vrCgLhwmPoqQMfjkm6NEG+TGKVIjxXnD9+HZYgIkzxmV2PuWsGlF+1nqHui7LyJU074ginuaug5cNuAcLhwAAA=="
    },
    {
      "src": "/stays/jolly-house/08.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJbACdAEevhxsUngA/uOINRAl5jXVnetz+ANU6JWtkmSVQl5VWKAKJBoYWTUQ8pj4DvjbL80et7VM9jYJYpz/D5MjmcLFO6+pwAAA"
    },
    {
      "src": "/stays/jolly-house/09.webp",
      "width": 1797,
      "height": 1012,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAkAA4BaJbACdADp8TXlw0AA/q3qGhFVPwbpHzw1IG65u0RT69UWvWMSZbb9FYYhrbbViVLTa3zdQXls9T3Vvo1UAAAA"
    },
    {
      "src": "/stays/jolly-house/10.webp",
      "width": 2000,
      "height": 1126,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJbACdAYr7RS17AD+3etR8u1EtYjXfmeiU7YwcRfh3BkHMhOz3dnLENAi/5VuOFPFsMAS+6sWTFiyLRRyOpFy0AA="
    },
    {
      "src": "/stays/jolly-house/11.webp",
      "width": 1798,
      "height": 1012,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAkAA4BaJbACdAEDxZjlgAD8/f9UCloof/2EIAEpd33FYVchEEx97hKyerdqAFTFuo2hLUHrm9zLcxKCpYroAAA="
    },
    {
      "src": "/stays/jolly-house/12.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAkAA4BaJbACdACjfiXYuADKuZdnMh9PVHxCVGxO1CF1MP0qEGARx5D6YG08IXDLGs1RoH1TZWYyXwIigrq7htF1o6uBl6DbzfCLmAAAAA=="
    },
    {
      "src": "/stays/jolly-house/13.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAkAA4BaJQBOgCLHsuEQrgAAzefzp50/eOPmWyixTGjzPAD0aXabVJfPV6hO0korIPCgBQfD5TaGAAA="
    },
    {
      "src": "/stays/jolly-house/14.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAkAA4BaJQBOgCB/nrOo/jQA/kJqLSlooUqwzb6fMURFkyzlN+EwGQBglVACBfchCqXMeQTtLJAAAAA="
    },
    {
      "src": "/stays/jolly-house/15.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAQCdASoQAAkAA4BaJagCdAYtA+uIRAAA+pYWFNgjmWHVEWfx+9JXz+NZ9+87Ul2bMwK20tP0Z92BD2U/pGIYn2L4aZulf19+55Ghuid2DuYI3leELEGWj39QAAAA"
    },
    {
      "src": "/stays/jolly-house/16.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoQAAkAA4BaJZACdACS8ByAAPa4QzbJVH2nCqxzkWLn5E5oy8twKLK/9ZrJUHT3zqe7UNpxc5RTODPfXSnY5kvcLnrT3afS1DjlRuVYyAA="
    },
    {
      "src": "/stays/jolly-house/17.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkAA4BaJQBOgBxseEnlHEAA/uQtVw1tB5REf3R/bZnm7fd+q1J06jm0/PrCxN3cM55XIf9L+6FAX1W6L9++DKAAAA=="
    },
    {
      "src": "/stays/jolly-house/18.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAkAA4BaJZQCdACZCO5TYAD+SZjrBILHrsvJs7kwC1qr2nzWmkQtEF8Zxau3jdKIaTY8AQzimoMJd6Fyf5ZqljztAAAA"
    },
    {
      "src": "/stays/jolly-house/19.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACQAQCdASoQAAkAA4BaJQAAT/M2VgAA/rcgoI3edQ0AIbUGDUl0wCZQNJd2iGSCIEQn5WAo76sJUkTf1ujwjMwTTHh2PtnPVYAAAA=="
    },
    {
      "src": "/stays/jolly-house/20.webp",
      "width": 1900,
      "height": 1070,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAQCdASoQAAkAA4BaJYwCsABzcZAA/shwUtFv20j9j79J9rtKx5+vQH7iU0I0hsRn0LU8UOxFFRM/B/2VF1jfQ3wxnerOAAA="
    },
    {
      "src": "/stays/jolly-house/21.webp",
      "width": 2997,
      "height": 1687,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACQAQCdASoQAAkAA4BaJQBOgBsBaoAA/l9JmbxCPaRXaDAj1Bu0qoD0Yvpo0Vx476E/fGycWF1si+GDlw4ZI0HhUdLAAA=="
    },
    {
      "src": "/stays/jolly-house/22.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoQAAkAA4BaJQBOgBbFYfMAAP7IN/RAYKN3lXedB7mWAFWL7/jXXQSBrtsNkr8mQ4S5Yykb9tU6jihtjGxQfGYoXYEUAA=="
    },
    {
      "src": "/stays/jolly-house/23.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACQAQCdASoQAAkAA4BaJQBOgBYpZUgA/Zl8LjgA93tJ5M+0ugpAFJt4lXFmmAEegzT4uak0DXJZ7VzKd8fVT8J2AAA="
    },
    {
      "src": "/stays/jolly-house/24.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAkAA4BaJYwCdIDZE3sApAAA/mRKql5j7jNAK9CWVmKBlK7f6SuU4i/OKEWvfmozVjs60QoOVf+7GcVuLnC+FESaDZ8ErD+AAA=="
    },
    {
      "src": "/stays/jolly-house/25.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAkAA4BaJQBOgBb2Kb2vkAD+0PeWGC7YZgpiCWmXTF7aQK1CXvoIZnoCWvWwLmDOKT+bZhH9PeZ+T9em0AcZT4UB9giQAGa2QAAA"
    },
    {
      "src": "/stays/jolly-house/26.webp",
      "width": 1700,
      "height": 957,
      "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACQAQCdASoQAAkAA4BaJYwCdACwzKAA4ctvUxXclrfB7PCZn2sjjhu1RdoSXKuQfwknkM7oL6FCU7/UKSvMZIAA"
    },
    {
      "src": "/stays/jolly-house/27.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAkAA4BaJQBOj+ACm9AckQAA/u0lrcecmUhcmnXGiDHM5n+5VV8bqI82KOmtbnB9vfIg5kWy18zuu/Fu/Nwbd+jMWAAA"
    },
    {
      "src": "/stays/jolly-house/28.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAkAA4BaJYgCdAC8Shc6eAD+9JGRulP0SunMEzMu+Z9391A2Y0o319JRgUpfP3FadQA2aV+Zr0QNo26WxgAA"
    },
    {
      "src": "/stays/jolly-house/29.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQAAkAA4BaJZgCdADDOrP4AAD+0f23S4tKn3zdTGKJe6Bkg1J6yK8UzE/0smw4LEKSbgGsyTAqO93WeFKgMu304IM9piOAF4wjz8CBJeZe68AA"
    },
    {
      "src": "/stays/jolly-house/30.webp",
      "width": 2500,
      "height": 1408,
      "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoQAAkAA4BaJYwCdACNTvEAAPfULFD2e056mqcMwDbe8qu8prbtoyKpDURhqoi3gq3PvYhGf/GYAYAA"
    },
    {
      "src": "/stays/jolly-house/31.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkAA4BaJQBOgB9lc5q34PAAzjVwfi9k3YsDA4iJggaXsdEay/6fiBs2uOFuRgNCq+/OsG78RF8xm3q3GiCdaAAAAA=="
    },
    {
      "src": "/stays/jolly-house/32.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAABQAgCdASoQAAkAA4BaJQBOj+ACzv1Re8koAQAA+uvjGbNbi1Qw1Z0r5SgTf/pzEZmhctFvNHDQGXEW8vAeuvd+8TpRhpipGnW5RDxAAAA="
    },
    {
      "src": "/stays/jolly-house/33.webp",
      "width": 2500,
      "height": 1408,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAQCdASoQAAkAA4BaJQBOgBcIigKAAMq5JrHY+jyW/IR334qY4QF1iZ4ID17U7Ul3iRxqCxyTfkHwm6hcfVvU7i7oarGgAAA="
    },
    {
      "src": "/stays/jolly-house/34.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJbACdADSJtScgAD+g00ODEBB6Q99uG1XuOrtk5YlBkM27fibmjs1y3uOX5tiw73wxW8hjTgtsz+ZIQAAAA=="
    }
  ],
  "knights": [
    {
      "src": "/stays/knights/01.webp",
      "width": 1920,
      "height": 1079,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAkAA4BaJbACw7DxJeSUAAD+978t3n5pVBNf8BuTodDodaJNA0bCpL8cKpbPyBHWoFEYgQzDYr/OVVCObZAQ3/fJ8o3+TWdYAAAA"
    },
    {
      "src": "/stays/knights/02.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJbACdAELgq0OdAAA/umuU3L5KM48vcHwHLSVaEpBJj16gRmOXuRB5mfdHoXROekCBV+vF0/qo2juUnjUgOn0P7ehn7Z2QhjeAAAA"
    },
    {
      "src": "/stays/knights/03.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACwAQCdASoQAAkAA4BaJbAC7ADQY44QAP71ooAJ1TLaQzY8hLDz1gIyKi9Mtt5ZfOqUmgUf39kYdMHG6PgVhkWR96slcgRLO/DzhyvyRj0DauwuNkoBbNW9fgA="
    },
    {
      "src": "/stays/knights/04.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAQCdASoQAAkAA4BaJQAAQGW7yGOAAP69tDE/D82eBlcl/Dx2+GVSDvsKLs7h4y48pmG40wfdQ8LmHr46XVhL2kN5r3m9w+1MRLJIAAA="
    },
    {
      "src": "/stays/knights/05.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAQCdASoQAAkAA4BaJZgCdADpz/aRE9gA/veH3NQjIvjkbl7s+jpjxnoVX9s/oyvGThqysxNSPVh6+MLBMWT5mW+IJFHnk/drpMVUeSmt4jNM6UopyB23hBVAUAAA"
    },
    {
      "src": "/stays/knights/06.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAkAA4BaJbAAAuu588rXaAD+9e9DQZZfpxghHCZ9nP/2NCR7QrfxRk2dgn07P/9pzAzOTP7+U2mWnLr/eAzmKFnhgzN4g+9zFCieauQAAA=="
    },
    {
      "src": "/stays/knights/07.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAQCdASoQAAkAA4BaJaACdACZ9PNIAP7voQ/NCSPCMWu2oH+VvOt7YhVFZYACu3t7/MWCHHo/V66ng1Dn1m7EwH0gOp059kEGQKVNL/Bb5AAA"
    },
    {
      "src": "/stays/knights/08.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAkAA4BaJbAAAxf3eIt7EAD+7Jhu4zwI87YoK6kjyvi6O3p/T4o/wuIjYQo+vCRzAMaq2f/mGMHHDpNad0+AAAA="
    },
    {
      "src": "/stays/knights/09.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAkAA4BaJbACdADp2bd0+QAA/vbX4lTx+bAXKd/KFUvF+3Td35tUukjLQg9/eP9AfK9mePx+vtVmGZa+ddGtwAA="
    },
    {
      "src": "/stays/knights/10.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoQAAkAA4BaJaQAAxO6YmXLwAD+lpZ+Kar1aKz6ASuCSx/Le+7vml8ueVvRe0i4hwYty3r4EAAAAA=="
    },
    {
      "src": "/stays/knights/11.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACQAQCdASoQAAkAA4BaJaQAAeHIQkAA/ug6vhjsqDz3vLmwHVtDbL+5qia8J+QO+EMFEMFxgFLezGoKPNUeXOgAAAA="
    },
    {
      "src": "/stays/knights/12.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA4BaJbAC7ADdKNkemvAA/vbXlw/zGgSblrc724vf623KT+1abUlf50S5op8AS1VZo2kKb9naO+KOSgmebYCYalBLgAA="
    },
    {
      "src": "/stays/knights/13.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAkAA4BaJbAC7ADw6Y4Uc4AA/vhWS1Q3dXJj4zAoSVsmUJBT83LSphzitW7mqCrIQ++nvLkiGv+tfGgtM0GiQAA="
    },
    {
      "src": "/stays/knights/14.webp",
      "width": 1920,
      "height": 1082,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJbACdADDQfpEAAD+9vHkF4kgOfEYq5y9eVMOYVX4tYX0Y11IycW9wHjbqE5mINg08E5g76YKyZVTvy2owO/1AAA="
    },
    {
      "src": "/stays/knights/15.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAQCdASoQAAkAA4BaJZgC7ADhepaPYAD+9th9WphmDmLwz3fqwtDjUm+kqJqHrl7AcKCHBcVSZxll8+B98vkNul6aMsCgczCp/u/V91HwMNlS+07Pjkhf8AAAAA=="
    },
    {
      "src": "/stays/knights/16.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAQAgCdASoQAAkAA4BaJZgCdAERH7dfTwUgAP74TvueTnxKswuYFxVJOSum+ozyX7iaYyXi1wvB2C9s3hNneXEEAAA="
    },
    {
      "src": "/stays/knights/17.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACQAQCdASoQAAkAA4BaJZwAAeg4tKwA/u2GB87XSizEBdCJKv/Y75h9K1yHwPg6eG7c2/9+yIOc8sx9ulgiKrKEAAA="
    }
  ],
  "light-house": [
    {
      "src": "/stays/light-house/01.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAkAA4BaJQBOgP4Acpdhe4AA/b1NbZ7OG1RuXmPISMMquKwDP7/eEqc9ifXqHg0HUZd2DHvf3imup6b9QRqMURhplyihpAAAAA=="
    },
    {
      "src": "/stays/light-house/02.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoQAAkAA4BaJQBOgMXI0B8TMOxmQAD+j7DPYTLirG3ApSbxp6gVbrXYoBoynq5kWKTRhcSnd66rxZWYGIomc5kc/sSVyLgCP8dbffQc+N5nRwwAAAA="
    },
    {
      "src": "/stays/light-house/03.webp",
      "width": 1900,
      "height": 1070,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAkAA4BaJYwCdAEeXd4sOAAA/KdAXYKqnYGRMX/NZiwhXN/4iqcg2VaukbcXLSkekGDR1/6TFBxzeZNNBMs8UxpLBnMPrsAAAA=="
    },
    {
      "src": "/stays/light-house/04.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJZACdAC9LGRn/gAA/e2KpUR/PjZmqyVawSlLS74DKuBtO2WY95VtqG4MZHXpa/fUU6oOv06tIY2iVaOMHk4ruLu+yj+ozKHGtEAA"
    },
    {
      "src": "/stays/light-house/05.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAkAA4BaJZACdAECujuj5wAA/sAMW09IZybnLcpPtldBjnV2mYkFX6AdsnUPyHX4M28SvobLxOplnj//JnvS3yGV10PS8VVer4AA"
    },
    {
      "src": "/stays/light-house/06.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAQCdASoQAAkAA4BaJQBOgA64ofgA/tvn2ECjudgEiOCFoSYloimvb2jJ4+Sd0FRHpWBO/VFeI+zfwOG1ygZXkqM5h26NQAA="
    },
    {
      "src": "/stays/light-house/07.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoQAAkAA4BaJQBYdhZqgH/AAP7I3L8b4Jhx8+xwG30nkhMyRHRk57pJEbLne29JU54J0bxoCoQZsIAA"
    },
    {
      "src": "/stays/light-house/08.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoQAAkAA4BaJZQAAuPqhZ4dsAD8/1XAfdtdX9JC0zq5hfKWLoeXcX/PUnYs9FqVqdT4YJACIYcAAA=="
    },
    {
      "src": "/stays/light-house/09.webp",
      "width": 3000,
      "height": 1689,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAgCdASoQAAkAA4BaJZACdH8AFVqmUE0IAP4Yj4q0gZbm20vXYTeXbZrOVkc7v8PLTEUeMEa+wwj/ToSlPsFyaHuQAAAA"
    },
    {
      "src": "/stays/light-house/10.webp",
      "width": 900,
      "height": 1599,
      "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JQBOmUABbfj61PJXujh3UQAD+1rY4df7BY5VyvaRJXSxxI8e2Nek5Wo9USuo8y3g+IgYZO6qPnsc1uTwIsafRmrR93XeCfgXSsXfk9uLXEWkebbfMv4kyOrjKz77s7DuurZSGT4FkeYCZwuJVWW3YUlMCItIAAAA="
    },
    {
      "src": "/stays/light-house/11.webp",
      "width": 700,
      "height": 1243,
      "blurDataURL": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAAAwBACdASoQABwAPu1iqU2ppaOiMAgBMB2JZgCdMoAlvxZTNFYJe9UvLoAA+KBLLUUFXIPkwRp2JaIWNLB/0AxNbrnjfSFDv/niaK0TqWPkPZxZ4lEmQWKGwS6kC9RQuKAGFhsOkt1H75JT+9wLL3cRp9dDinDQPObFTMOvcskbActhr0dEooRcpSXqznwTnBl9btld1gguuYV2MdAJ0BmPMvRAAA=="
    },
    {
      "src": "/stays/light-house/12.webp",
      "width": 1900,
      "height": 1070,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAkAA4BaJZACdAEDW+bM1oAA/q+7/M02j6qVKwavyHZjnBeVXTdA+vAGNFuMWxJYEPG5zS7kwZf+QIBNme7hmGmRgQmN2AAAAA=="
    },
    {
      "src": "/stays/light-house/13.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAkAA4BaJQBOgBmAuoh+CAAA+UR6sPWpg857VrXKeuCLE/3pSagDpJlWIQX0bzIjhdfTVTdZptMYqFGvY9xA2J2upEAA"
    },
    {
      "src": "/stays/light-house/14.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAkAA4BaJYgCdAYtpUZLtq6AAPyEPVkfRvuxILmvoC42P/4NS6gf5hCOklao9809Fqna1LsVLiI3m899T788fK/JuJepw9TRNgAA"
    },
    {
      "src": "/stays/light-house/15.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAkAA4BaJQBOgBu1UurMhHwA/tH0gt+P8PnT7WpvHxuHHBM+mURuHxS7dujDRqC3aJd1PKSWAYYKksLw5y8S/YEfpGNsy9ekAAAA"
    },
    {
      "src": "/stays/light-house/16.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAkAA4BaJZACdADpuMlwU8AA/nkaL2CeyPt9UL+aUg0XqXJMSZ0bVEZLRxd6v6RJcyvMLY3900jMi86+FwlFaAfT1ogVry2DeAAA"
    },
    {
      "src": "/stays/light-house/17.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJZgCdADbnkV/AAD4RdQgFhk94weQpcXc8C8O68RFbvEQVJTAkPplid451+dzfXfCbsMOPv9TZc1JpWNAAA=="
    }
  ],
  "neo-pod": [
    {
      "src": "/stays/neo-pod/01.webp",
      "width": 1920,
      "height": 1080,
      "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACwAQCdASoQAAkAA4BaJQBOgBQbNEQAAP7KqQzeWYjv+dQ/vhnlTf2nwsN0Ds3prYO/ZfY0TZiMLiCqBUH6pTUynta2vNBf9bLPPthTEAm5O89LQ9hU4QoYgSl5LGqlb+AAAA=="
    },
    {
      "src": "/stays/neo-pod/02.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAkAA4BaJZQCdAC6RAEUIAD5d69zfHnocy6QbrPgiPV7r3lu0VXzD6n4ry0mMMMjYxtQ+3L9zMpJ7DYQsaP0/irn+Tdyj2gBJwf1CtCAAA=="
    },
    {
      "src": "/stays/neo-pod/03.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACQAQCdASoQAAkAA4BaJbACw7BWBNAA/ktzNvmCsWMV6WIs8eczyh4oL40i5OYIsBsl19NpuHbcyE18V5nQViTMo51gRQwxHRvk31o/nENhAAAA"
    },
    {
      "src": "/stays/neo-pod/04.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAwAgCdASoQAAkAA4BaJbAC7AYvXlM+esKE0AD+7QE0Fxrm+DwO2sojJOPeVClCLiw0esF3XzfJqGkzmwHVssP+NBTSbc/e0W34AAAA"
    },
    {
      "src": "/stays/neo-pod/05.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoQAAkAA4BaJQBOgBJpp3YAAP6DlMm9qVPtEymHy1xVP8Ol7gXtVkOde+oFVDE5Mqqr6i82xz2ZdPXFROMoQDIsYigmMR2A0g7xt+IAAAA="
    },
    {
      "src": "/stays/neo-pod/06.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAQCdASoQAAkAA4BaJQBOgCBqkHUAAP2h3s/f8xr/2MCt3nake8PWJFcKewwcckBxFsUt+j3JYHpAEmOyujPzgp36gN/mt2uGw4AA"
    },
    {
      "src": "/stays/neo-pod/07.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAkAA4BaJYwCdAEWaWdY69qAAP7BxifmVQKCWKNrN52CC2ESS+/iSa9TWukVUk0xE/wCzWZTLTwicxmGiC3rtmmqZcEFlT1cAA=="
    },
    {
      "src": "/stays/neo-pod/08.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAkAA4BaJZwAAxcCaW5V9OgA/rX5J/7gmNOKNOyKCY5HIp2wVzi9P5IXvUzrg0W73gvx23MAPHHi6FAAAA=="
    },
    {
      "src": "/stays/neo-pod/09.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAkAA4BaJZQCdAEag6bUeAD+7ymYT9lIyvi1sMQfLEiToH5B8TALUw9JlITZUa7cY9cikJsZDgAA"
    },
    {
      "src": "/stays/neo-pod/10.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAkAA4BaJZQC7AEQ8VQPNAD82RCeQdzqOYHJLl3iduLTQnh/7qgirh9uknVeTINItPR5V2V22ax1myaogAAA"
    },
    {
      "src": "/stays/neo-pod/11.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAQCdASoQAAkAA4BaJZQAAgA8+MgAAPJv6Pdc1d7767BZnHzCSXDrVRqYy/j4FGqCfvXOQQ89ficPLpds5a30ciHq7h4mGZfmBbIAAAA="
    },
    {
      "src": "/stays/neo-pod/12.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAkAA4BaJaQAAvzsChN6AAD+x1M7/n26Qwolf4uyDuS8E1zv0m6qg9ICozXFAyi3vcVgD95DtOAAAAA="
    },
    {
      "src": "/stays/neo-pod/13.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAQCdASoQAAkAA4BaJZwAAhWJ3/u4AP6Rp8m58a4eb32Z0/lATsot2n7/sCwI8wXRi3VBIH4yy9DG1oAcAA=="
    },
    {
      "src": "/stays/neo-pod/14.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJYwC7AC2UOuhQAD+jzA8YAC54kaAkt8PpmFpMTEfudXBfVkbjecJzJutWGID2vpEYxGMVbuZa6zqpS3jObZCoQVQAA=="
    },
    {
      "src": "/stays/neo-pod/15.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAkAA4BaJZQCdAD0Z/2taIAA/flNuZQlknJ0ust1wkLhg9a54X3Qv4s9r00VTxmIx/nrnT1Y7NgxBQAAAA=="
    },
    {
      "src": "/stays/neo-pod/16.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAkAA4BaJQBOgB9TH9RsosQAAPa2HClV2QlIQM4xLM0Rba0x7WTqV2txX+nQdrpGjkC6TAIlu9Cek3iC4TvqMExvdBVAKD2sYgi3IXQAAA=="
    },
    {
      "src": "/stays/neo-pod/17.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAkAA4BaJYgC7AEQ0EXLI+iAAP7nZtwVjVjQ0KF042HeZLKSYNHczj6xV7w5WupiQMOeq+kwFGeYGmu8DK652z6g4qym5z4U7DAA"
    },
    {
      "src": "/stays/neo-pod/18.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkAA4BaJQBOgCFU16sKywAAzhpJcdo3xSYITUs7fr+7zhcrCJ+wlZZrpX4E6EqAyRmO3Rzkj1KDQyLz+6Kil4AAAA=="
    },
    {
      "src": "/stays/neo-pod/19.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAkAA4BaJYwCdACXe1o/gAD+o39B9ql3u6tI6/x6Powvb3bNUowVtZCkVv6Y2sQlydh0yF5d+rkiauQdT9+NAAA="
    },
    {
      "src": "/stays/neo-pod/20.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoQAAkAA4BaJZgAAtT/uYsQAP7G7NPg99EU41MybojIdXXZ9vIA3l45cm4z+4OdcYs19AK/P9VhrE62H+q8RhYA"
    },
    {
      "src": "/stays/neo-pod/21.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAkAA4BaJZwC7AEJ9qbruAAA4nSHMee8HzxHPyg/6fR+TuFYL1lCrzo7GMkFvtqFBVwzXVNXuqjGkoAAAA=="
    },
    {
      "src": "/stays/neo-pod/22.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAQCdASoQAAkAA4BaJZwAAcL7zCmAAP4E5rGZytL+B+79Myn8CWIyWWs0jmUQWkSOVdPjrEcsh+k3JZQUAA=="
    },
    {
      "src": "/stays/neo-pod/23.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoQAAkAA4BaJYwCdADGTNA5gAD4zidT14X9DkMxeGQxrZNc1YtlD3L3rEs1x8Yv8SXbr1oAha2wAA=="
    },
    {
      "src": "/stays/neo-pod/24.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAkAA4BaJZQCdADwbIFf4YAA/uZM2bBa+xBJGYtueoAjWChaBu6Vvl0Dxzg51NgeygngAkYlm0pgAAA="
    },
    {
      "src": "/stays/neo-pod/25.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoQAAkAA4BaJQBOgBxtz3pIAP5hFa1mXBoMFR9JbFVUN++xw5KrvIX5aOJRu5Kqp5uWMwqw7mJ9Rp4j78NJWAAA"
    }
  ],
  "pine-stay": [
    {
      "src": "/stays/pine-stay/01.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoQAAkAA4BaJZACdAYtBEbbiy4AAM41YoPNkaxxN6oZZMNN8SbjkOIYrcMfFPMPOpKzNc/Vu6c/xTaohHjNEXxYXPW1/bxm0qxRyIjDditxWAWCmJlfvhPpjkSQAAAA"
    },
    {
      "src": "/stays/pine-stay/02.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAwAgCdASoQAAkAA4BaJZQCdIExGMKdZ5c8nADOLxWZcmne0V+roLCBl6SXBq5FaR1rhJU4tMFBXLTEwyDSlxWcHTfInAzeuY0KcT8lMvngAA=="
    },
    {
      "src": "/stays/pine-stay/03.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAkAA4BaJQBOgMXSqGblseUAAP7icVT4bhCUAeryh5gt4C0QDbcet826+tS5ZyZkeEj+Pq7BsoINqekdEA0NuEDdjMMUvir+exV8PuAAAA=="
    },
    {
      "src": "/stays/pine-stay/04.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJQBWABl6cf5OEAD+62SH27Tl8lpQMXJw35OyWimBlYo7yEEK2IEVKHPtXcWxaK1t5UOgP5Wf62+LJZ36DFAAAAA="
    },
    {
      "src": "/stays/pine-stay/05.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAkAA4BaJZwAD4/Q9vb8T3oAAM4+fV7dSTYzqrg/Y3nUZhAIi/Q7B+PoBuqgiWtU+yKof815pACLfQnfhyVM1sJqAAAA"
    },
    {
      "src": "/stays/pine-stay/06.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAkAA4BaJZQAAxO4+w5IlrdgAP3tQLTA3Sp/2g81/TO4d5w37xxb/XHhBJi/BCxiNwu1aaUnO3WL5/ALRsMM1oXyhKN4ySO6LSAA"
    },
    {
      "src": "/stays/pine-stay/07.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoQAAkAA4BaJQBYdsW+km8ASADL+XpwKb+eKGfygHFQpAJewUZ6SaL6josXshD+AxB8TfW41o72Fd7Xi/0GfZ/FvPj/Rin+NKXRJz9AAAA="
    },
    {
      "src": "/stays/pine-stay/08.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAkAA4BaJQBdgCLY6d23r6AA+NJ/hhE+J50DkkAnQy3UcN2orDV5pbOkWny1dU3Sa27CHXNEfjA7s1NNp4AA"
    },
    {
      "src": "/stays/pine-stay/09.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAABQAgCdASoQAAkAA4BaJZQC7AYulzXPy3gQ4gAA/u0dUxJLlyJ+T6J84dDljzS6Cm0H43o21nghjEkxEyo54c6iwXfAhFoD0N80TAAA"
    },
    {
      "src": "/stays/pine-stay/10.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAkAA4BaJZQC7ADR+SU2f4AA/rwK+NYV9biFS1ulKmq7PcamCqAFUr/wgxVh0mHoU3uYuKsMAAAA"
    },
    {
      "src": "/stays/pine-stay/11.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoQAAkAA4BaJZQAAlobBYEFQAD+jblAFQp7jQOAmtz1rS1KGmHjVvhBoYYL97PAyDseYTTzs4AAAA=="
    },
    {
      "src": "/stays/pine-stay/12.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACQAQCdASoQAAkAA4BaJZwAASYJAAAA/l/eN1EWUqXU+MEUsanNYrd/tspX5eW3EamV+rYUwAA="
    },
    {
      "src": "/stays/pine-stay/13.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoQAAkAA4BaJZQCsADp26N29AD+ySROpGKv017ugRa3aVZxqG/k3sD+PH4YeIN8+aTn8DUCfpbwAA=="
    },
    {
      "src": "/stays/pine-stay/14.webp",
      "width": 1200,
      "height": 675,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoQAAkAA4BaJZQCdAChOESgAP6NNsIU93BY/BNJf1UDrmu7jHL7grjsDKkydD+Uz/g51eL26Q1ct4e1An+uAAAA"
    }
  ],
  "santorini-bliss": [
    {
      "src": "/stays/santorini-bliss/01.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAwAgCdASoQAAkAA4BaJagCdAEQg/MHUS7gAADNoUP//nEg4UNWP8vaX3gilXYe1TqA7nP2BWWXtZ/DiJRAbvhEqCYTL2ubXsFHdvzOq651pdLYRQTzj2S/Olmy9oMahpFwQsR2L2fWqoEAAAA="
    },
    {
      "src": "/stays/santorini-bliss/02.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoQAAkAA4BaJYgCdH8AFMyOp3MoAAD+5syRletdID78UY0hUcjrGja6VwTz/xZ/xidSp3AduU7nWfseoQrAT77ghalznL/BsToaOs1uAIsBvGFFgAA="
    },
    {
      "src": "/stays/santorini-bliss/03.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAkAA4BaJQBOj+ACm9nq8YAAzj6atsu8j5ODwdSgo2RBCNfYgHNFD3Ww9uxsAeqvJdXUtcKu3Z3H7NdRddOZ2NDPExE0A+0/YG3FeBNuRNuAAAA="
    },
    {
      "src": "/stays/santorini-bliss/04.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJQBOgCLFs01DAAD8/1SdBrZszk9D3VkPvRP1+XVVk7WjEOLcH2t0Pn07Pd+fkXg26eUDmZVwtgGBQVGFrplmY8AAAA=="
    },
    {
      "src": "/stays/santorini-bliss/05.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACQAQCdASoQAAkAA4BaJZQAAkfrrQAA4YE5qvnd2IWKiuLI8vi6vQELj0qnq9NlS4CsgEX0HZjolIAA"
    },
    {
      "src": "/stays/santorini-bliss/06.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAkAA4BaJZQC7ACRveSYAAD94l8UHy+H+5eGWYgVOGJ6wj0Uz5cSh80w3aZ2xqiMnzVgbASIFW1sgJEck4AAAAA="
    },
    {
      "src": "/stays/santorini-bliss/07.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAQCdASoQAAkAA4BaJZgAAn6LtEAA/G8I9mdQeqosUgK029CU5OZcew0L/mnxNfk5xPfFGGi0PvBowEAB21D0dqL4bBoGuAA="
    },
    {
      "src": "/stays/santorini-bliss/08.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACQAQCdASoQAAkAA4BaJZwAAouxL4AA+p/k2qROF48aTW52LVdZYbEfWPG92la1dlfc1mfuyWpnKXAaUSkrPyYEAAA="
    },
    {
      "src": "/stays/santorini-bliss/09.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJaACdAEfwoa07EAA9FiO43tfRgk7h/Vf4MPsc2CsTfEYAwcCygYxqaSxYnhMj4PpP4AFd8tXKqiyZ4Lrt+IDPGOALaSKte61gAAA"
    },
    {
      "src": "/stays/santorini-bliss/10.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAkAA4BaJYgCdH8AGXw1EUWgAP7l7UBflBJkGEFBrhcpo80ppPKirk35G0vvIHeX3DnQK7ZFzNzpIpYh8ZWP4FX1dZoQu92tB1/egAA="
    },
    {
      "src": "/stays/santorini-bliss/11.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAkAA4BaJZgCdAD693IUzgAA9p6EWStJZYKm/hN+qUJ13mjsNeRSsM/D1YLfbd70MXhQNrIVJyzmszmGhAUdQ86TAVwpIwoAAA=="
    },
    {
      "src": "/stays/santorini-bliss/12.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAwAgCdASoQAAkAA4BaJZgCdAEXWfdMzcJGAAD+mxn/XQDz4phQl1DMRjV2ZyLu1Ph5BNVwifJx70+giDYbQbj8g+n9GZGaWzrxKp+AJAAAAA=="
    },
    {
      "src": "/stays/santorini-bliss/13.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAkAA4BaJYgCdAEVYmhy2qLAAP7uo8cIdEkw+cfK/x7hf2C2rhBSwrCJwc4ovD5S9+YXZcWNKnUCvw5y30jJ5AoWTsjwFlM9MtZoAAA="
    },
    {
      "src": "/stays/santorini-bliss/14.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAkAA4BaJZgCdAEQYrpcS4tAAMtKtkNPJYBOdf5GzmY+B8zFmPHle0HkRXM9/gTaa3aYJlzntjSvOhwnyHOE2FXr3xJlr537kss3ct9umAAA"
    },
    {
      "src": "/stays/santorini-bliss/15.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAkAA4BaJYgCdAD8tdSDgcAA/vL/PrEHsNPjb7tLM1G/Zl5CCGjHck6wegQ99ZMeXB4Qvg6xaf5dvs+VRgLjeYGuGKAA"
    },
    {
      "src": "/stays/santorini-bliss/16.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoQAAkAA4BaJbACdABrUeAAAKHtfNDjfIz1NDprUjls7yafppFM2BGJjIxvGtm3xx+ciJWN153fYz/v2geQj/f7QIAAAA=="
    },
    {
      "src": "/stays/santorini-bliss/17.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoQAAkAA4BaJaQAApEn/Pf5AAD+jwm72hgsjYumdQREFsdEDQxQxNHgAAA="
    },
    {
      "src": "/stays/santorini-bliss/18.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoQAAkAA4BaJaQAAt/Ex5d0AP5f2pAxfJHkFsu9UKbBk5AZvjE55i/f7gAAAA=="
    },
    {
      "src": "/stays/santorini-bliss/19.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACQAQCdASoQAAkAA4BaJaQAAbhJsgAA4DPGfdCrwdV1YBD6JdHGYO2XR0INHt6An04B+3ASacOVUSCUiswAAA=="
    },
    {
      "src": "/stays/santorini-bliss/20.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoQAAkAA4BaJZwAAuXfJyeAAP7q80uU34fMYCLMcJ+IbQz+Rwes82AMlJZ8fMWEmkkfoAAA"
    },
    {
      "src": "/stays/santorini-bliss/21.webp",
      "width": 1920,
      "height": 1082,
      "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwAgCdASoQAAkAA4BaJbACdH8AFN8j5IKYAAD5br4K2ii6H6xI7dIIYMSXS5hdpDl0DtiEO1WTBMqixNugVDoMXffofo6rMnHwqDwYXvnZynbQsIS/qCjPfXyztFmAyMSxAAAA"
    },
    {
      "src": "/stays/santorini-bliss/22.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJbAC7AED9+eAGADONmFL98YbRLx3EN0actm5AJri+LAntgzAKph9FSZTsNq8/OEnUzCT4WgGyTBHF1hK9LqKUgAAAA=="
    },
    {
      "src": "/stays/santorini-bliss/23.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAkAA4BaJbACdAEHElBPSAD+hquvmJAYfrjEwvRPrRFMzwIp8csYGhZHRrgvnkBBGizILSge6yNcs2+bXF7w+L+e6C6Eb++MQ59YEPAAAA=="
    },
    {
      "src": "/stays/santorini-bliss/24.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJZQCdAD54RfBAADN+66HvUbFXMWCIhtdDe2mbTmbQjAvBjDQPpV2wdawf9lb3Rfnr/Dg0DObvtN6ZjhmlA5gAAA="
    },
    {
      "src": "/stays/santorini-bliss/25.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAkAA4BaJYwC7ADcocLbIuAA4mwSqNRCiz+K1EzL2S7Xe1MaSE3xofCdsiHW3xb0XfJcBoJ8MmSASAAAAA=="
    },
    {
      "src": "/stays/santorini-bliss/26.webp",
      "width": 1920,
      "height": 3411,
      "blurDataURL": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAABQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JYgC/OywFR+LmKPEa6+gP1J9gAP5R9/IIunUHUzbFaQ7wZrtGPJELyajqRjE/n8k2tlFJYv2joZbMHCOlMcbSbZTBEvqbbmjg5N3t/Ws0woyU2nOXnYpkcVQi7p39c8yfzt+Y93nK14xs6gqy8/m+Oz8VF5VpGYLgAA=="
    }
  ],
  "snug-studio": [
    {
      "src": "/stays/snug-studio/01.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQAAkAA4BaJZACdADO+A82AADLF4yVxhuNIP2H12y68jNZgoJzWNNv7KWucwlZ7O7MSPzn/2827lDlYrN9SK3+jSv6X+AkiA8TTIUAMmXSNAAA"
    },
    {
      "src": "/stays/snug-studio/02.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJbACdADRAXANAAD9RFY1MHNg7mLfeiJhVW00ldGgrsr6oMXmgLBRzAjok+K6iV1uL8FhgsgVTvzzidcJwLJ4gAA="
    },
    {
      "src": "/stays/snug-studio/03.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABQAgCdASoQAAkAA4BaJYgCdG1/ApFvklV9CEAA/mVaWfzoS3BOP//4aTvnSre8gr5ye/6VKUiM5rkr+KpPQk2FnMRQf0+sE+0c+whzFTpApaFJeXnDhaYAAAA="
    },
    {
      "src": "/stays/snug-studio/04.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJYgCdAEWxK11PAAA/mZaLQXuW7Qm8SUSoED3o2TVgISz3dIdbQ015UJbGnTBTCY8awOwZPoRL816hQC5l4BGdk4xR6av4efkqKAA"
    },
    {
      "src": "/stays/snug-studio/05.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAQCdASoQAAkAA4BaJaACdADdbWLUeggA/md+2AiPav2WWc91fVFW808trNxY9zAitjGCWqCGiKy6bLNfid7kaBryHxeaStFm9hpMxBBQs3fJKIVMgLXIxNhM2IAA"
    },
    {
      "src": "/stays/snug-studio/06.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAkAA4BaJYgCdADPHU5AJYAA/I/P5at5eaofT6/gyplsZeef6vFhPOjW0yIwrJBELQ7VRQQNBE83DsRY6XI8nkSH6od4i6SAAA=="
    },
    {
      "src": "/stays/snug-studio/07.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACQAQCdASoQAAkAA4BaJZgCdABV/+AA/o+RSTebCUgRilbcUnjs0QQiwf89jzizHeM5s6u7R3BfvQbpdUceolmB4ZeKjmbm1hxQNF1NhpOkAaAA"
    },
    {
      "src": "/stays/snug-studio/08.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQAgCdASoQAAkAA4BaJQBOj+AW4A0dLRMfrgAA/eqRVCqeBxsxKOKKmD3a8/Thi61m8kPmltQS7AGu6znHXG4M7pGZ9PdhY83R2VOsNJtdKAHcTiy/C1VE9WAAAA=="
    },
    {
      "src": "/stays/snug-studio/09.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJYwCdAC3BFWPIAD+0dwieWwtdmJswSfEZvy9ebisQ6hciq8ygNm3BxVyEZ7UJIVsl+I7BtepOAc8yQAAAA=="
    },
    {
      "src": "/stays/snug-studio/10.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJYwCdADiGsEz6AD+0dl1UFGhOLF11i10UuUnh2MHGaZMILYgzu5dQBn2/AMuWZzySFoTf07+FQiZ0AAAAA=="
    },
    {
      "src": "/stays/snug-studio/11.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAkAA4BaJYwCdADHs2J64AD+8Xq7tBHpLsWAAL9x5iWBZ2cPVr4t0gZx7d75686bQbiEklEsL8kMTXnkdgAA"
    },
    {
      "src": "/stays/snug-studio/12.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoQAAkAA4BaJZACdAYvXqc7P/CeoAD+jhtUVKQgx2UhuwRJsfZ7qcLF8Qu9UhyPBbtkZ9YRF6lVR7Hj1v9d1QpevPwBR9qXe0d/A3FCLqPa/IWAAAA="
    },
    {
      "src": "/stays/snug-studio/13.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAkAA4BaJbACdAD1bR5CCAAA/cU3ftZJfwkSCNI2ONvrxnq+G6DmXcqWX734x9ZEAEFqflYpF1hrcgt6smqnAwTcNRm9f8N1IAAA"
    },
    {
      "src": "/stays/snug-studio/14.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwAgCdASoQAAkAA4BaJbACdH8AF/2FABGS4AD8i9EWEDIhdh18pFaEdpZEGBlsZ0TbOJKdB0ZenTqf9YT6QdoYQE/nsyvtJCJudPYsiyn5GCN74AAAAA=="
    },
    {
      "src": "/stays/snug-studio/15.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAkAA4BaJagCdACzG/VGmAD11mNwGnpbXsAoS9gCPADNl50wbyE205v6qp7JhYgYMvKJsyXlMZUCTxSRedT2JOhP/+2LEqKPAAAA"
    },
    {
      "src": "/stays/snug-studio/16.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJZgCdADG4Hi6KAD+3RXtHClC/5C7PG0C0czNtwyyZ1lyXK3sptrdnW+T4XBGpilhLIfUr8ip+lXntAAAAA=="
    },
    {
      "src": "/stays/snug-studio/17.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJZQCdADiPPwJdAD+R+ctBSOgwpp8conbn+izTXAhbSufmUSbPWqp3Ez/jZKgX9rao2+FvAg+kOnPuMCbAzoKgAA="
    },
    {
      "src": "/stays/snug-studio/18.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJbACdADs7MraAAD8i4I26kmiVisRZv/586TeqtXXI26VDhqId2zO3ZK5B7Q12GCJ5hsiCeWvGS0XamU2vMK+SIGgAA=="
    },
    {
      "src": "/stays/snug-studio/19.webp",
      "width": 2500,
      "height": 1408,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAkAA4BaJQBOgB4D0bCXgAD+5zZJOQKhWIhbSjXDRcVhdJWq+ggH/vQsaPP9+JUUUQV+6BCahUCxnAA="
    }
  ],
  "swift": [
    {
      "src": "/stays/swift/01.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAkAA4BaJZACdAEXaXXacMBgAMyJNG2E+ULnLbfiyShq+U6V5wukhq8py6l4QBXO8L2NYQGSWOVbOJWd5WQNQsnNMN4GoAA="
    },
    {
      "src": "/stays/swift/02.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAkAA4BaJZACdAYp5InMYj6IAP7tq6sXa30NLfhJrpTxKP6O3dFboPrIaL+7A1X9YxwjfpHUpsWBQaiWwNKcqnku9QUy+NaEOxL9sCwAAA=="
    },
    {
      "src": "/stays/swift/03.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACwAQCdASoQAAkAA4BaJYwCdACQQdEQAPzZNilw9MV48P+MVgCw00+PP9G3AkXX1L+yFesAhl+UE2jI2XxDMw5BQ3xMVojTfzQdoY+aC9nvsdGUxQAAAA=="
    },
    {
      "src": "/stays/swift/04.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAkAA4BaJZQCdAC9f1A04AD7w4QhrhvEadF0J1BNW2uYrKi0skf7s9p1wjxOLqQIwRcOBQ8Pmo4AAAA="
    },
    {
      "src": "/stays/swift/05.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAkAA4BaJaQAAveJJGmRMgAA/tKyVRq797ncE2r3rsmmLnHeUOnXurkc4JA+gp1iuzgzHXTgzwT6VxooAAAA"
    },
    {
      "src": "/stays/swift/06.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAQCdASoQAAkAA4BaJQAAMWR1oAAA/iabwvevFyK28QWz5t5bqNCZx7nQxrFtuhOn5vvTScUl8IWWoeE24W9MZwPyBsPwAAA="
    },
    {
      "src": "/stays/swift/07.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAkAA4BaJYwCdADbY/oBTQAA/mUe6IdVuQ8cJ6k95peyIOjgonxwWMBK/6sqWnS3CRtIi4HifAOE5XgAAA=="
    },
    {
      "src": "/stays/swift/08.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAkAA4BaJZwAAsVi6Gy44AD+1ylaBIXRDV1Ifl5aOfHjAkma6gUnFlJwP9zJBtmGMswdXB/4z4EAAAA="
    },
    {
      "src": "/stays/swift/09.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAkAA4BaJYwAA2y4iypaGgAA/liHyymR4UEjXUPvg5EsIvd00cPRuuGk9z5tE7Eud+5nGUsVaht+OfNYDCVV/ixJQl6Ynt64EIAA"
    },
    {
      "src": "/stays/swift/10.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoQAAkAA4BaJZQAAZabQWegAP5MfecJxEF8lVO25PNZWCujoNuB1VGaO16MXVu6Yko/gQdbToInfuBGUR3Z7Fo/3CtpgZPme2HqImtGgAA="
    },
    {
      "src": "/stays/swift/11.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQAAkAA4BaJYwCdAEWuBAEjkQAAP6tK4AJzuWP5+YUYyl3XcZTrj5mNhZHqzh++8fB9gofZawTquxdHGnSvIz+kUUAAA=="
    },
    {
      "src": "/stays/swift/12.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAkAA4BaJZQCdADvy4AfIAD+xB/lmARksJ1t2QmDnbJtP3qqixuKzMMqTw0j3mv++ElMM7qwglR9EDKyhsA/KhW5k9EPMG6NLPwA"
    },
    {
      "src": "/stays/swift/13.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAkAA4BaJZQC7ADH27uAxYAA/A6QYl5eTjHyYGWYP+1EpXJsNDdAnBf+65AN5HYSlZp98cTQUYZOwFpOi7owS5r0GNREhAwe5MAA"
    },
    {
      "src": "/stays/swift/14.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoQAAkAA4BaJaQAAwS665gZQAD+52x5dzP7/ILn3XDZiYk04rDSEyFZy+7nBLU2zoAAAA=="
    },
    {
      "src": "/stays/swift/15.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACQAQCdASoQAAkAA4BaJZwAAUJn5WAA/fxeECaQpMWbMGv2xwSt9V8tandpFjh0empDYYjHlHX1T59U1w8JW39J1YQAAA=="
    },
    {
      "src": "/stays/swift/16.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAABQAgCdASoQAAkAA4BaJZQCdMn8BTfXobrz6AAA/okXdEe4+uK51yna8viVWfnoZIXrcaAZMsjhxR8jt7l3gt0VEwWNy6Ind2a6aViPoOb347AA"
    },
    {
      "src": "/stays/swift/17.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoQAAkAA4BaJQBOj+ABmX3/gAD+m6g/1qVJIli0GTwA2ZPyflM3Y49K+7uqBhwSVt+4YKfVY79T+ai2bG0mM15G4KRbw7FN63PdVWoLAAA="
    }
  ],
  "uni-pod": [
    {
      "src": "/stays/uni-pod/01.webp",
      "width": 1920,
      "height": 1080,
      "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoQAAkAA4BaJagCdAYtLCp5j4HwAP7fAFO/E1oorFPrTfMggP075Zcx34btKb2x5pCnxf0q5+GkF0fIFWn/1+ibD1HQjLmod1F9eJHIFlo0+9uyTtCxjNpYlSks5QAA"
    },
    {
      "src": "/stays/uni-pod/02.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAkAA4BaJbACdAD2IFWeCUAA/vE44N3BpKVbg66iI+9MqR8b9OefrsX9Vyg3Fv382fR2oTRPRYb45D/8tsOreNgqFVLc14/AAA=="
    },
    {
      "src": "/stays/uni-pod/03.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAACwAQCdASoQAAkAA4BaJQBOgBI1LuCgAP4zpOStzO8Np/uajZediXuItF20tWK3aeeyOli/ZjCTrPDi0lf7VEx7+nu/x4y6ihdFQvgCGbvidBMdBMzKL98nLqAAAA=="
    },
    {
      "src": "/stays/uni-pod/04.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAkAA4BaJQBOgBmDtdsWgAD+VOx1oscmghe6gmCjlasQTDF6rjQi8ojNvCegqhJiZQASoBABvkIcvk3YGAAA"
    },
    {
      "src": "/stays/uni-pod/05.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAkAA4BaJYgCdAD7YKP6xqIA/dGDb+7IJM+hUljZQu+qShL5UC8CdTncW97wSXqANs9PeaG+h1UDzG+9cCrOYqfeoAAA"
    },
    {
      "src": "/stays/uni-pod/06.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAkAA4BaJYgCdAYuRUZQUtF8APv8rsPYPD3Vxgal6Q0VN8lSdmVoNL+LOloyF1xQKazOpGZ2q81/s9oQfDiP7fzfQiJFF3c09z7we2SQxpbaW4RctbXNAAA="
    },
    {
      "src": "/stays/uni-pod/07.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoQAAkAA4BaJQBOgBultKQzAAD+qobbIzklb6ncHhsVfboatBcOt8PquHeAq4KsFjIhEP5Osq91DhU4bw/6DkAAonFvM7fxPMBjWd0GAAA="
    },
    {
      "src": "/stays/uni-pod/08.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAkAA4BaJQBOgBhonxKjAAD+wew9m/SH5oSb3cBPeyhZ4qV9suIdu+pvgzPx2eZ3mgjwYcKR3V/DXhDq7MoNOXAAGrapSdCk6UJGRRyAAA=="
    },
    {
      "src": "/stays/uni-pod/09.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJYwCdADpAcUAAAD+71ndMfKrShaIBlBI/lYft77Wg6IEvGEIuCO3qK2isooTmIgDrG3jyCeuEoQKSYJzG09fJ33yAA=="
    },
    {
      "src": "/stays/uni-pod/10.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAQCdASoQAAkAA4BaJZQAAfSI+y2YAOH9Vg1nwwXkre8XdmLb5+ovSEzVNrutCSrAh4Yq8Wd5LICAw/VYDqgkwsOAAA=="
    },
    {
      "src": "/stays/uni-pod/11.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoQAAkAA4BaJZwAAbIpnugAAPZnAJFQVwbWdES/TKO8wuBNOzSb24jP2Kp/Y3BAiBP/ObylgAA="
    },
    {
      "src": "/stays/uni-pod/12.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAkAA4BaJZQAAxU5ULgEsADN8F8tZZXU99qOMVXtWyyBVrXGC3/gzuh83gL5uuyvbVVVsow8QmV36Yl9t/2AAAA="
    },
    {
      "src": "/stays/uni-pod/13.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoQAAkAA4BaJZwAAsV0SyA1YAD+6pRRravQ6ziP8hQvrjeL2OqAu91D0K+S3HWpilb65ytgFAA="
    },
    {
      "src": "/stays/uni-pod/14.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAkAA4BaJZQAAtvR0SHbwAD45KD98k5hwatz+V5aVp+S0W869oFn22JEXPx/R9g04TSM8rpt52jDZP88AAAA"
    },
    {
      "src": "/stays/uni-pod/15.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoQAAkAA4BaJZQAApQT4XNyQAD+VtfSiMlre+UCoMdzhPcyWbKU4qZ8NCWFscqbUA4AAA=="
    },
    {
      "src": "/stays/uni-pod/16.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACQAQCdASoQAAkAA4BaJYwAAY4lyIAA/JoWlp1d+5ByNcBaUrcuu3Qdr5fqyu5JacQ4/G8SAAA="
    },
    {
      "src": "/stays/uni-pod/17.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoQAAkAA4BaJZQAAtuqxERAAPfdY7MevzFI+ZS8Vf6u1Vi6CRXcurbK7/P530KAAAA="
    },
    {
      "src": "/stays/uni-pod/18.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwAgCdASoQAAkAA4BaJQBOgMXctpZ1OlFWAAD+lDypUdDfjWH984dS9ZQt+WYtJNuwwa0Au7vQbeUZhB7Wv6kjPcHAKCBbriaR8ARk4XwBziizpc9AAA=="
    },
    {
      "src": "/stays/uni-pod/19.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAkAA4BaJYwCdAEDpX5/Bvt4AM4pXLWXH3wbIzmSzYztXEwhuf28Ie9Xnx5PazAJWg8nFh6HODlzeG7ywRUaKoy+yUUAAAA="
    },
    {
      "src": "/stays/uni-pod/20.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAkAA4BaJYwCdADDGJ52wAD7Irw/V8mQIBOFDEHRL8ie+1PolV8ZgDLj4b82lbE7TMx9oQSRjRwzumnlnqiIAAA="
    },
    {
      "src": "/stays/uni-pod/21.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAkAA4BaJYwCdAEeZe1f4AD94gy4VpYdeKfQ4C63ECzbyZxXbUaW3J5HtIHifLl6wdqvOwK9PN00OAAAAA=="
    },
    {
      "src": "/stays/uni-pod/22.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQAAkAA4BaJYgCdAEWUQb+nDcAAOJ8FJwc2RCujxOlacJ7TfLT/L6M7CgXyuK3TIFxsrYgYG0iit2fqXe+9tp7P9EgAA=="
    },
    {
      "src": "/stays/uni-pod/23.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAkAA4BaJYwCdADRDnsvcAD+lyBBjQ3p4IVx/uisHz7METP0W37ig6T9QjcDf77g+OKJgTugPG7cnieS/q6i2Y7BLHAEb5mo4AAA"
    },
    {
      "src": "/stays/uni-pod/24.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACQAQCdASoQAAkAA4BaJQBOgBw5YSAA/fvA/tTwdoZP+eD9pxhcbjNSIiOXPs/ASHf8RZ+TibHUiOP5fyFdZ4b7cdcWm4P2wFQAAA=="
    },
    {
      "src": "/stays/uni-pod/25.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAkAA4BaJZwAAuRIpmojoAD+CHqUuKo7jM7pPrkhTW7QM8OKZuyoVAe34Ks+JGNKsFraAiUVkIoAAAA="
    },
    {
      "src": "/stays/uni-pod/26.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoQAAkAA4BaJYwAArP3mm1OQADb3QBtCNOdTOE3ZA8gU5+36DvI0EVyxC5vSlKety9AAA=="
    },
    {
      "src": "/stays/uni-pod/27.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoQAAkAA4BaJZQAAbf+SVIAAPhjKSKQS7oqJYXBbqasyQGU81iKp2SeDqjjOPefyQColEjORvsAoAAA"
    },
    {
      "src": "/stays/uni-pod/28.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAkAA4BaJYgCdADJyOVNIgAA/tvIzVc+kf3UdOA/XjwIe0+2LKKidejnyW0uOCS0WOrF7e3mLlJnPV7G0nhGBjrx+FAkVuXOqAAA"
    },
    {
      "src": "/stays/uni-pod/29.webp",
      "width": 1920,
      "height": 1081,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkAA4BaJZgAAuRv7fJp+qAA/sQbic5Me/bje5BWL9dSjCGFoniiD0yiUvMTlxC3RI+2RERwFHWxL+g6n7/XzwAAAA=="
    }
  ],
  "wonk-studio": [
    {
      "src": "/stays/wonk-studio/01.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAkAA4BaJbACdADNHD2a2OMAAPkz3J4q2HsIv0GZbCSGbwLRVkaBgQDlh0hEdSVqUjLlUdzcPFc68d2Q3zK2eitnmd0tPGtg9nJstS8/gAAA"
    },
    {
      "src": "/stays/wonk-studio/02.webp",
      "width": 1900,
      "height": 1070,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAkAA4BaJYgCdACztnDnYAAA/GFewaEWLiGz/8NS2ZeTKuWPW6xjDJDgsvkIePgdBiwMa23jC4ol6jFt4wNblbLz0oopAR4AAA=="
    },
    {
      "src": "/stays/wonk-studio/03.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA4BaJZACdAELYKQHwSAA+U3xkQj7gNm4NqjoDe9gMtyDdLx4FVDGHxhmDuUxD1Q8xk0GDYhA54A7lcQxJ1yggRoAAAA="
    },
    {
      "src": "/stays/wonk-studio/04.webp",
      "width": 2095,
      "height": 1179,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAkAA4BaJYgCdAC67gJ70gAA/lYA0X7Hx+wWrNXdU6omlGOr2fU43lJncNi7Z7hw88jRRLOsfTGmRagr6AAA"
    },
    {
      "src": "/stays/wonk-studio/05.webp",
      "width": 1799,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJQBOgB065DW+iAD+0G9eG1ZsorTydkoyHfpe1gKM9DyaZ1FavCpEoVoAx1lnSsWXJEtZNFAzBUiORuhmWO4f2AWAAA=="
    },
    {
      "src": "/stays/wonk-studio/06.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAkAA4BaJaACdAEC0o8yfRAA4k7mfPFZ17WvPW1yb98oUhsBNlJAVMXK5veailWkjcN7wdC16MGhJyVtzMGdBITdgYAA"
    },
    {
      "src": "/stays/wonk-studio/07.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACQAQCdASoQAAkAA4BaJQBOgA0+VgAAzjjTI0VN/KTNLa+LZOoPAdfSNF8sfXsU9Ul721NtQO8mC5tELj7YUmgEEbowhnsfFN7IAA=="
    },
    {
      "src": "/stays/wonk-studio/08.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAkAA4BaJYgCdADD3rjgYxAA/t37UaZ07aMvRtPnoBAV4uxgx3qygKvFDc0TK0PI5witAlo/+/WgpWJnCL6AAAA="
    },
    {
      "src": "/stays/wonk-studio/09.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACwAQCdASoQAAkAA4BaJbACdAC5guxIAPxlvzk+coM5vGdVYUlCXrfbIDOoWYKMDohQ00ffAQPUByvdr5a7kW+GyH16Li8Lq1hL9P4FmqiBI12Z/z2x00WAAAA="
    },
    {
      "src": "/stays/wonk-studio/10.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABQAgCdASoQAAkAA4BaJQBOgMWM5eiK6/TiqQAA9Ac2uNY3bYd4S23dfsmfS7pjZ0tviL4EBLVVJY0Ou7SEXcDwxQpnb+AfOVGyTVdCgeBr2tycAAA="
    },
    {
      "src": "/stays/wonk-studio/11.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAwAgCdASoQAAkAA4BaJYgCdADp9uYmbPFTAAD+5m5uIn3WOeEXXok6LJ5fPeduoMqOKrPDsHJw/LiUanv8GXNEOSE+hufu2izvEAAA"
    },
    {
      "src": "/stays/wonk-studio/12.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoQAAkAA4BaJYwCdAEfq/TaKuGGAAD9wv1Z7ANX3Cr4MktESjeCVpy5BdwI0tOipuFKmD2FkE3tffhSJYxIfcXqlS2jOYTpVyqI4cwiBAA="
    },
    {
      "src": "/stays/wonk-studio/13.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAkAA4BaJZwAAve/SrfvY/AA/t4MkkwMmJEGhbsPQo/gvGjEVN7BG3iItbha5D1bqoLvEEuSv4AA"
    },
    {
      "src": "/stays/wonk-studio/14.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJagCdAEG9wa0wAD44w1EswzOSnInQtv6suv5MkACqFPXWgtuo6KLO8B6RqHLfGnv8CKUTMzbGgmO5JAAAA=="
    },
    {
      "src": "/stays/wonk-studio/15.webp",
      "width": 2500,
      "height": 1408,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAkAA4BaJZgCdADdGiSeU8AA/gllEX3mXZm7SVJOF/GyTmSL6/Zab4dZ4WU/RIsCXXeJYWqek1c0Da+nP0PXVp6B7sGcDe2ikkoAAAA="
    },
    {
      "src": "/stays/wonk-studio/16.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkAA4BaJQBOgB9fvDk+7jAA/js3A+xFeiKe82ckjosjF6xDf1unGnFayZkPCQyGQWfAn7EWazB+q4AUrkBvZGfAAA=="
    },
    {
      "src": "/stays/wonk-studio/17.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA4BaJaACdADMqYvQDQAA+OFlha4Ior5fiPvFbcdFomNw572JjLH0DX0KnY4i2QwGaXoQccIAcPDX5/BugWfAOMsAAAA="
    },
    {
      "src": "/stays/wonk-studio/18.webp",
      "width": 2501,
      "height": 1408,
      "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoQAAkAA4BaJQBdgBM4BnQAAP7Td9o8M+A/PIemOHhzCp5hlSD6PWdE2/kJai4kLbDrizLECS57uAAA"
    }
  ]
};
