// Generated by scripts/generate-photos.mjs. Do not edit by hand.
import type { Photo } from "./types";

export const photosBySlug: Record<string, Photo[]> = {
  "ample-house": [
    {
      "src": "/stays/ample-house/01.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAkAA4BaJbACdAEWvECPmugAAP5AumQX8/c9sU9Qs7+YoYQFo6qQ0b42U2rXA3bwcKPlIXk6g8mtsea1jHNdrRwJhuddkl/GQvEQFvzN1KWy7uJ8O672AAA="
    },
    {
      "src": "/stays/ample-house/02.webp",
      "width": 1700,
      "height": 957,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkAA4BaJQBOgCBrH9NQZQAA/ukpbF+Ny1ShMMmcQ30JUK8/NQNMFJNVPRZ+8/JdL7lp0ct+xYspddHMC0ZyWQAAAA=="
    },
    {
      "src": "/stays/ample-house/03.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwAgCdASoQAAkAA4BaJbACdAEQZIVz0seloADOOrrU4U/J0qF9g8AXWuJKSf1+8JXM98ZlJInXfCsUkFpZLbf69QddzRFdg3MABbag4EucXWOCLr6jHt1JM/P8Xtk8AAA="
    },
    {
      "src": "/stays/ample-house/04.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAkAA4BaJYwCdAEDu1cqlBzwAP7o9Ge+1YKqXgmrCAPLBqSyBrFUD1amvmRroiirLxGfsA6f2IRIivAzOhyXu5g6dUAA"
    },
    {
      "src": "/stays/ample-house/05.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAkAA4BaJQBOgMW+5FuxVJQAAPu962YJE+pzr5M6swILK6ioh3Y8rv4KXmO32GCuZDaI2pu7mN4isipyA4ibe/KaroAAAAA="
    },
    {
      "src": "/stays/ample-house/06.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAkAA4BaJYwCdAYtAsKZmADeTlhCBhgM535mU+Cwh74dPYg4FjCcNoAE4Uqz1Mu4mbV9lMWkKSbZya7WaYxE7m4EwO/xrErlAAAA"
    },
    {
      "src": "/stays/ample-house/07.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAkAA4BaJQBWABe3My31KgAA9VOO03/iXN7TTys9yuHLKeWo3xuhRtxusNfHZwP8LaLdXgY2b/9JBBOwAA=="
    },
    {
      "src": "/stays/ample-house/08.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAkAA4BaJYwCdAD7UqTq1gAA/sPycj+YttVhLjoTM0l8sKog8ZnsmiO0s+DiyIVRqU/6AbfmFvpIAAA="
    },
    {
      "src": "/stays/ample-house/09.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAkAA4BaJYgCdAYrdtQWwJ6AAP6tAF1ira4GVl4vE8V8VB2xteS7PVkr3/BQ+LYICUorjix451v68uk5B6hPJD0ysj/v/ngAAA=="
    },
    {
      "src": "/stays/ample-house/10.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAkAA4BaJbACdAEecJlHraQAAP678LXOsM5zQSDIavynzTAVUTTxKp+g1NV72RKeybH6rfUgfKskKJJ4i8N+XyeZF711t4AAAA=="
    },
    {
      "src": "/stays/ample-house/11.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoQAAkAA4BaJbACdAYv1yfCvL9jsADOMeU1lGJAvnMrIb7GbRjRnLCj3dLwY0vX5z1a7h/fHpOSaykdIzJxGu2SEr8lHVAn88mYbMNpWEyVAAAA"
    },
    {
      "src": "/stays/ample-house/12.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA4BaJZgCdADJwtsmbwAA/u0Ll16PPU15IcPOF/HUFLcCEn1yXkhCsaQVQ9lwdk7egQSg9nMkwkOApDl3bMo9r4KhoAA="
    },
    {
      "src": "/stays/ample-house/13.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoQAAkAA4BaJZwAAi96UfIAAP3Dvm8L06uaQQpf/meeq43wmUmKCI6O776NVXZcHsb8KiTM0YNatkS9KUnWLgAA"
    },
    {
      "src": "/stays/ample-house/14.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJQBdgBtuF1HoAAD+pqenvqhS/jc4dncfdBhaLC1skw/lCRcqDTzEHm6raR/I8aHLCOt8Cg+1G+dlmccdqgUSNMAAAA=="
    },
    {
      "src": "/stays/ample-house/15.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJYgCsAEDCzpsYAD+P0ww4NRNy2MJ3TTBU4DsDgPokah4mrVuZetKpGUvNijoros93T6Ts5t86HQ9LrB+cg4t3dgAAA=="
    },
    {
      "src": "/stays/ample-house/16.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAkAA4BaJYwAAp10OlXxQZwA/tK1fr+g/jB/cF2B08+/PJu+B33wL1tJOKGPn+qcfKiytQ0agTO5VnwAAA=="
    },
    {
      "src": "/stays/ample-house/17.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJYgCdACUhRL0wAD+OKQX5ycQ2DL/+hqBbA5KbJa9KrIt64XR0JwzjJ37UvVY25uV2oTvURMTxElBqRzJv6BQAAA="
    },
    {
      "src": "/stays/ample-house/18.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoQAAkAA4BaJYgAAlZMVciAAP7ur0PUWNLxTv8G0a/PhduTaNbeBoVJUy/qhHT2EbGb/GHsf8FwvyIPypDHayjjYHgAAA=="
    },
    {
      "src": "/stays/ample-house/19.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAkAA4BaJYwCdADD2/Ut4ADgEnsc0LPk+dU/YoJqPuDrJ5yMsqAlNFiUIhpMhvtBRSWvbAXwiJrNAHRArqRAAAA="
    },
    {
      "src": "/stays/ample-house/20.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAkAA4BaJQBOgCHq2SnPMpAA/tWtonTDBfjUKTwEip+49AoCxOTxHTMpKHI3hoHl7vX/Zo3pDqfw5r4AAA=="
    },
    {
      "src": "/stays/ample-house/21.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAQCdASoQAAkAA4BaJYgCdACTNG+wAP5ZcN8ySsjD2a5oDDJn2VCkhI8/+Wz61gcENhGHHScbGEx6MPjhx5mYh2ltZboWIxQ2OJXQAAA="
    },
    {
      "src": "/stays/ample-house/22.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAkAA4BaJQBOj+ADMOymMegAAPyO8ZPJsBWGw75bkL3jJj2Sn9/RbzF3aHy3IUXhl7MiRUM0Nx72PeJStoJ8igVpRvzZMgAAAA=="
    },
    {
      "src": "/stays/ample-house/23.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAkAA4BaJYwCdADw8Cv1YvgwAP7Ha1dbFUVsYARFdOagkxoin05LnJvWrGAWo8uvSCU+GbOb/o3sZhj/CmF2f+pgAAAA"
    },
    {
      "src": "/stays/ample-house/24.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAkAA4BaJQBOgBbdBlGdAAD94y0aqY9PABNjSuAt+iIsuV7cGhYzBP4TJT6jlkf6topk8t95Ru5c3z0FR3AAAAA="
    },
    {
      "src": "/stays/ample-house/25.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA4BaJQBOgBxvt2I1wgAA/q2xM1yEs1jE2CAaL9azyesM4dXAOq/SK6oYP1YM36NAh/EUZzAPFxTBQYXhYfLdJN3AAAA="
    },
    {
      "src": "/stays/ample-house/26.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACQAQCdASoQAAkAA4BaJQBOgBszoTAA+OTkKqQexnj+IfDw+eAeJ5Abuh8mZ5ENnaSyHbmq4x1QLkRXxGG3w2nt6RY2b4AfItYQAA=="
    },
    {
      "src": "/stays/ample-house/27.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAkAA4BaJYgAAvfARvunZPAA/phN4jeuyCDfEkV8wSmh48k/ef52+YiwY+MFmiOQFcrnh2oVuC8t5XKATVzno+N+8HbYlwAAAA=="
    },
    {
      "src": "/stays/ample-house/28.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAkAA4BaJQBOgCL2f5ja6AAA/qjl1CdBM303s8PVJdSjlT5FHN4bOoz4aY+jpXlChBr2GldOufHIpTwmH59Jcwr3GIWewih2tlAMAAA="
    },
    {
      "src": "/stays/ample-house/29.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJYgCdACUhRL0wAD+OKQX5ycQ2DL/+hqBbA5KbJa9KrIt64XR0JwzjJ37UvVY25uV2oTvURMTxElBqRzJv6BQAAA="
    },
    {
      "src": "/stays/ample-house/30.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoQAAkAA4BaJYgAAlZMVciAAP7ur0PUWNLxTv8G0a/PhduTaNbeBoVJUy/qhHT2EbGb/GHsf8FwvyIPypDHayjjYHgAAA=="
    },
    {
      "src": "/stays/ample-house/31.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkAA4BaJYwCxC8AFlLDVAAA/mWWoa4ak+01RhSVY9FWz5qzRpwl4J7lFccQ6dBJ5VZ4c5ODT5vrrJtLO3BvXWaAAA=="
    },
    {
      "src": "/stays/ample-house/32.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAkAA4BaJQBOgB08gc+bIAD8B8rH4s8lM5rA3blV/D/OqT5RrmZzS9fNvqKP2yvqvRwIvXWU3nuP5wAAAA=="
    },
    {
      "src": "/stays/ample-house/33.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoQAAkAA4BaJYgCdACPYEAAAPfULTyXQW9dtiGfvWR+GYb/zcvqkrqQl8LZL5kQEZzu+7mXiDYYlQghBTClDAAA"
    },
    {
      "src": "/stays/ample-house/34.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoQAAkAA4BaJQBOgBa+TqgAAP6psQhdrPEJuQPw2tJ4x0dEoA+v6RSG10V2ZXBqJ14uOGV/nRugX8zhMzwbCenGv1eAAA=="
    },
    {
      "src": "/stays/ample-house/35.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAkAA4BaJZgCdADp0NwuGAAA8UFymbq3bHUeiHFvfp8VeU9MKG0W4X8nd5bp/DWFcmZNcjoqelxatNrdZmtMGWg7kUAA"
    },
    {
      "src": "/stays/ample-house/36.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAkAA4BaJZQCdADdccvr9UAAzATTwXjIvan+KeTi3ePFshIDCBzxjFejs/5GQoFvE0BCxrlex6ZGydVmAA=="
    },
    {
      "src": "/stays/ample-house/37.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoQAAkAA4BaJYwCdAEW0voVDfgAzWfbRqTKIxYlJ+OwP9tflQcX4LrFKNlV4grmjcWwwYAA"
    },
    {
      "src": "/stays/ample-house/38.webp",
      "width": 1600,
      "height": 900,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoQAAkAA4BaJQBOgBY0wF7AAPzS0/PZaWmDABYK/DZuJkH+rDZBL1x5cSPb0ifRHMULSeIHw1pg0PvoAAA="
    }
  ],
  "chillax-pod": [
    {
      "src": "/stays/chillax-pod/01.webp",
      "width": 1671,
      "height": 941,
      "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAQCdASoQAAkAA4BaJbACdAEK3yAcxgAA4k/Z7ZpECqdVUfKsHV5JdEkm/LFb/I3vqyBEpsHr/ZASANdkWKu3YWpwItax6tzmoOfIUKHvkfZOpNRjUJLk3zAATd8UAAA="
    },
    {
      "src": "/stays/chillax-pod/02.webp",
      "width": 2500,
      "height": 1408,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoQAAkAA4BaJQBOj+AQUROdag9WgAD+NG69TQrjNwbnd7U7Vbtjc2X2RBgpreHaCon1pzop7pwgXtVncYjDTSCSUVARgJ3NYDWFz/sAAAA="
    },
    {
      "src": "/stays/chillax-pod/03.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkAA4BaJZQCdAYs3FZSFoAA/kmWjjSR2sVYXaZMyPZR3ckBM4k5YQa5H0VHqetBqIiXaz7bhhXHwR031xBommoAAA=="
    },
    {
      "src": "/stays/chillax-pod/04.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAkAA4BaJQBOgB61ZziHJgAA9ynwImFI5/WVcjL6XxGYn5YhZ/5uQJ460KqskJuG9F5Vzhn2Y2TiyVVe/JuFwAA="
    },
    {
      "src": "/stays/chillax-pod/05.webp",
      "width": 2500,
      "height": 1408,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoQAAkAA4BaJQBOgBMsaEmwAP6F5xUDSkzOn1Vwkavsa2b2Jise9LifyTw8XznnTUjY2iDg1AaLzpZQHv08WU7u/FVrfkAenCCc8shgAAA="
    },
    {
      "src": "/stays/chillax-pod/06.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAQCdASoQAAkAA4BaJZACdADSLU5+2AD+1qyM4ZX1IGPb2XE5BaZWGp7GjAF5B/nBQQOAYo8uQSXb1Yku6e+w/CXZaSZzOj9+R8wqgf1aIlqXMabpUIvySAA="
    },
    {
      "src": "/stays/chillax-pod/07.webp",
      "width": 2500,
      "height": 1408,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAkAA4BaJZQCdACq2/GkcAD+mbbePgac/WgCLCNOqNyXypm9Ar7AXc07ie/M0ARb5ys2sDqtD7dO+E/MS4wtnOkN0wAA"
    },
    {
      "src": "/stays/chillax-pod/08.webp",
      "width": 2000,
      "height": 1126,
      "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAkAA4BaJZgCdAYvXaYt62nAAP61rU4THmgrvS+ZdEFnnGmG/j60+kK7LwqaRgWhdEQ/EABfWOQFIO8+hkZ72w8tv936126Eyg00+5Rto1AvjKAAAA=="
    },
    {
      "src": "/stays/chillax-pod/09.webp",
      "width": 2000,
      "height": 1126,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoQAAkAA4BaJQBOj+ABo+d8oAD+Gf7REgMZWixehaDvoDMka9eMLxJE5SNXvXUoUEOLjj6mYzuyPpMa6o0mqH3qEVys0nhTXzbCCJqAAAA="
    },
    {
      "src": "/stays/chillax-pod/10.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoQAAkAA4BaJQBOgA7vSO8AAPvsC+2NiDN8JTjTOcqx9uNptDrgb/WA42rNtI9kO81vM0AvJOd+pvXzn9s7uEN6Wwi2dFirVKwrEIxwAAA="
    },
    {
      "src": "/stays/chillax-pod/11.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAQCdASoQAAkAA4BaJYwCdACd+84AAP6EZv/GmoDr4mbBIBxmnvdfLljWnxxvQ73fhucU4P7Xf1RyZHne8zCcJX8jvPeoUAA="
    },
    {
      "src": "/stays/chillax-pod/12.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAkAA4BaJZQAD45OLiQTYlgAAPynbw8ulLgWI0g7bPVslh7Lg2oDwT9i5PmTj4zeoKzlvFGWRWs5dtqzJ5tCD5ZsyNlHcgh5GEKgAAA="
    },
    {
      "src": "/stays/chillax-pod/13.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABwAQCdASoQAAkAA4BaJQAAO/ukAAD+ZnYMGzsKK3sY5AU0PmSzT/23Z5+cf35qklXLee9GPNv9tYdzmDQ7O6H91EE+ByOdxHXAAA=="
    },
    {
      "src": "/stays/chillax-pod/14.webp",
      "width": 2000,
      "height": 1126,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoQAAkAA4BaJQBOgBocnRxAAPgjWJMeW+4hfA/5XpuyHEsuaz55FGNh72yfWgUPx74xQkmp1TUggHzhjtXoIAAA"
    },
    {
      "src": "/stays/chillax-pod/15.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJYwCdADBaVqcAAD+TNuxIGOg+Ub0gJTDwMMG0od+8ZZCqhWrkNLgDayQW6kF4zxfeOxdGgs2HZ3NvPEZPxyJXMwAAA=="
    }
  ],
  "comfy-pod": [
    {
      "src": "/stays/comfy-pod/01.webp",
      "width": 1600,
      "height": 902,
      "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADQAQCdASoQAAkAA4BaJbACdADl3P9nQADw3Rx5zKYGNnYgj6uSi+GjAXU5c7Fk0WkaVtd8Bd/lj+u4ltvV3Ui8IBHPtl3YwX7Z+SVxW0ksP80l5j6Dy3RP19MeKDz+sL5r13uJzGqn2bO2AAA="
    },
    {
      "src": "/stays/comfy-pod/02.webp",
      "width": 1671,
      "height": 941,
      "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAkAA4BaJbACdADpINKzCgAA/vBmx+laGxFaOaUGvh25+3ABaV4XMWdrzfMjE/4Aw8cuO318lRQ84S0wN8MsPGhIaZt6YO34Szg6O+hP7hV+384AAA=="
    },
    {
      "src": "/stays/comfy-pod/03.webp",
      "width": 1671,
      "height": 941,
      "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAQAgCdASoQAAkAA4BaJbACdADw7ipgf4IAAPwvCH/8IUabhQ+edxmSKK2p+CcF+mZdsgQpr88nqnhHJQlSQzb/ET9TuMY1XBYNv0rInxTUNlhSJHLeKi+FfRXnYFFnQnQgjxjEuVBl3HIfC1GA7D+AAAA="
    },
    {
      "src": "/stays/comfy-pod/04.webp",
      "width": 1670,
      "height": 941,
      "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAwAgCdASoQAAkAA4BaJbACdAD8Hbgkxq0UAAD+tljDgYiQKGwhGywdLd3SDhX1v8XrqD+PAQj0BcGfLwylCbHC8fWrgnc5X0t31BRLdaka5upoP+ZqP9omfJDebMX/zb+PRezPvzIz9bgAAAA="
    },
    {
      "src": "/stays/comfy-pod/05.webp",
      "width": 1671,
      "height": 941,
      "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQAgCdASoQAAkAA4BaJaACdAEDHu+bwjagAOJ/8aOZR7/Ng8sbuuHffhB0T0UXc83iRxeuX/f6tsWyuDd2oi0dE8mMSadVtrFtLhm8dS3ZLlYIxtltuqwsYJx788Z+o6F0PmG/8CVxLeQAAAA="
    },
    {
      "src": "/stays/comfy-pod/06.webp",
      "width": 1671,
      "height": 941,
      "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwAQCdASoQAAkAA4BaJbACdAC23/DGxBgA/tdh0wk5d2zyNM0+/4M1oqUCUlyFF276YI2HYk+rYW+1ExQRz609xKPfys4pHpLZH/UARiFyUtl/1xdhl2Iw1uUdbAOUMzViJpggrhwfUbLAAAA="
    },
    {
      "src": "/stays/comfy-pod/07.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoQAAkAA4BaJYwCdADC7XwwAP4Kw0/G13eHk0rdyk4eZ1eUx9CPvCC1woZvzFip7Y3V7j9hpYe6ZYvAAAA="
    },
    {
      "src": "/stays/comfy-pod/08.webp",
      "width": 1475,
      "height": 2620,
      "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAACwAwCdASoQABwALrV2u12jqampiYC0SgCo9EO+9m5niBgyxerGAAD5aEen9/SC7gYSQuT9Z/v4BILk2bFjc9pqGW2HmExRnwQtjLurCE3fAp4mIQWGi9/p0DOHGlHjNFJHz/nt3L6nglT6BQwJ+syJ8AA="
    }
  ],
  "jolly-house": [
    {
      "src": "/stays/jolly-house/01.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAkAA4BaJQBOgMW50BVNttAA/oo8NzE4ZN5aTe9QYTXoteQXL9zMIOf2Muk646mqPv7aEV2cbLbLuS2mf9IZi3Rxq46/J+j6Z/AA"
    },
    {
      "src": "/stays/jolly-house/02.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJQBOgB0+UEfCAAD+qeUyRJKQXKr7N6/jREuAhKiDRhtnSuGDeuhmI+3QmMyA6PtQ/bilOyQvnWkQX9smZdnAAAA="
    },
    {
      "src": "/stays/jolly-house/03.webp",
      "width": 1796,
      "height": 1011,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAQCdASoQAAkAA4BaJagCdADViegAAP48lld+yA4QIVHMmjTzBEn5IHyulVR4PfOPphq9u+gUV7V59PozJVbO5AyIFW7I35/0CAAA"
    },
    {
      "src": "/stays/jolly-house/04.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoQAAkAA4BaJZACdACkTowAAP5g6lWmqnWprS7m64DiJr5lyFY4oBZCoYhiPbMf55vNs+CMhKhyPK8GDCMNjdA1GAAAAA=="
    },
    {
      "src": "/stays/jolly-house/05.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAkAA4BaJQBOgBelmr9dAAD2vuGLA22COsWPG1p9gi6RiMjOQJfw+PhqNcVB+e4sXouay6LAPxPbdeDgxftzLxOJhiY0kjFfIjAA"
    },
    {
      "src": "/stays/jolly-house/06.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoQAAkAA4BaJbACdADveyrRQAD+6R1onT9IsG2P3xJp3/idrOr0iE98dEUL55V2DbED63nCtHkr4sXiYO+ku5dwU11z9xe33ANYptboAAA="
    },
    {
      "src": "/stays/jolly-house/07.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoQAAkAA4BaJbACdAYrdgf4/uaoAP7BqFaybD65vrCgLhwmPoqQMfjkm6NEG+TGKVIjxXnD9+HZYgIkzxmV2PuWsGlF+1nqHui7LyJU074ginuaug5cNuAcLhwAAA=="
    },
    {
      "src": "/stays/jolly-house/08.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJbACdAEevhxsUngA/uOINRAl5jXVnetz+ANU6JWtkmSVQl5VWKAKJBoYWTUQ8pj4DvjbL80et7VM9jYJYpz/D5MjmcLFO6+pwAAA"
    },
    {
      "src": "/stays/jolly-house/09.webp",
      "width": 1797,
      "height": 1012,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAkAA4BaJbACdADp8TXlw0AA/q3qGhFVPwbpHzw1IG65u0RT69UWvWMSZbb9FYYhrbbViVLTa3zdQXls9T3Vvo1UAAAA"
    },
    {
      "src": "/stays/jolly-house/10.webp",
      "width": 2000,
      "height": 1126,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJbACdAYr7RS17AD+3etR8u1EtYjXfmeiU7YwcRfh3BkHMhOz3dnLENAi/5VuOFPFsMAS+6sWTFiyLRRyOpFy0AA="
    },
    {
      "src": "/stays/jolly-house/11.webp",
      "width": 1798,
      "height": 1012,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAkAA4BaJbACdAEDxZjlgAD8/f9UCloof/2EIAEpd33FYVchEEx97hKyerdqAFTFuo2hLUHrm9zLcxKCpYroAAA="
    },
    {
      "src": "/stays/jolly-house/12.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAkAA4BaJbACdACjfiXYuADKuZdnMh9PVHxCVGxO1CF1MP0qEGARx5D6YG08IXDLGs1RoH1TZWYyXwIigrq7htF1o6uBl6DbzfCLmAAAAA=="
    },
    {
      "src": "/stays/jolly-house/13.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAkAA4BaJQBOgCLHsuEQrgAAzefzp50/eOPmWyixTGjzPAD0aXabVJfPV6hO0korIPCgBQfD5TaGAAA="
    },
    {
      "src": "/stays/jolly-house/14.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAkAA4BaJQBOgCB/nrOo/jQA/kJqLSlooUqwzb6fMURFkyzlN+EwGQBglVACBfchCqXMeQTtLJAAAAA="
    },
    {
      "src": "/stays/jolly-house/15.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAQCdASoQAAkAA4BaJagCdAYtA+uIRAAA+pYWFNgjmWHVEWfx+9JXz+NZ9+87Ul2bMwK20tP0Z92BD2U/pGIYn2L4aZulf19+55Ghuid2DuYI3leELEGWj39QAAAA"
    },
    {
      "src": "/stays/jolly-house/16.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoQAAkAA4BaJZACdACS8ByAAPa4QzbJVH2nCqxzkWLn5E5oy8twKLK/9ZrJUHT3zqe7UNpxc5RTODPfXSnY5kvcLnrT3afS1DjlRuVYyAA="
    },
    {
      "src": "/stays/jolly-house/17.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkAA4BaJQBOgBxseEnlHEAA/uQtVw1tB5REf3R/bZnm7fd+q1J06jm0/PrCxN3cM55XIf9L+6FAX1W6L9++DKAAAA=="
    },
    {
      "src": "/stays/jolly-house/18.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAkAA4BaJZQCdACZCO5TYAD+SZjrBILHrsvJs7kwC1qr2nzWmkQtEF8Zxau3jdKIaTY8AQzimoMJd6Fyf5ZqljztAAAA"
    },
    {
      "src": "/stays/jolly-house/19.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACQAQCdASoQAAkAA4BaJQAAT/M2VgAA/rcgoI3edQ0AIbUGDUl0wCZQNJd2iGSCIEQn5WAo76sJUkTf1ujwjMwTTHh2PtnPVYAAAA=="
    },
    {
      "src": "/stays/jolly-house/20.webp",
      "width": 1900,
      "height": 1070,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAQCdASoQAAkAA4BaJYwCsABzcZAA/shwUtFv20j9j79J9rtKx5+vQH7iU0I0hsRn0LU8UOxFFRM/B/2VF1jfQ3wxnerOAAA="
    },
    {
      "src": "/stays/jolly-house/21.webp",
      "width": 2997,
      "height": 1687,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACQAQCdASoQAAkAA4BaJQBOgBsBaoAA/l9JmbxCPaRXaDAj1Bu0qoD0Yvpo0Vx476E/fGycWF1si+GDlw4ZI0HhUdLAAA=="
    },
    {
      "src": "/stays/jolly-house/22.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoQAAkAA4BaJQBOgBbFYfMAAP7IN/RAYKN3lXedB7mWAFWL7/jXXQSBrtsNkr8mQ4S5Yykb9tU6jihtjGxQfGYoXYEUAA=="
    },
    {
      "src": "/stays/jolly-house/23.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACQAQCdASoQAAkAA4BaJQBOgBYpZUgA/Zl8LjgA93tJ5M+0ugpAFJt4lXFmmAEegzT4uak0DXJZ7VzKd8fVT8J2AAA="
    },
    {
      "src": "/stays/jolly-house/24.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAkAA4BaJYwCdIDZE3sApAAA/mRKql5j7jNAK9CWVmKBlK7f6SuU4i/OKEWvfmozVjs60QoOVf+7GcVuLnC+FESaDZ8ErD+AAA=="
    },
    {
      "src": "/stays/jolly-house/25.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAkAA4BaJQBOgBb2Kb2vkAD+0PeWGC7YZgpiCWmXTF7aQK1CXvoIZnoCWvWwLmDOKT+bZhH9PeZ+T9em0AcZT4UB9giQAGa2QAAA"
    },
    {
      "src": "/stays/jolly-house/26.webp",
      "width": 1700,
      "height": 957,
      "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACQAQCdASoQAAkAA4BaJYwCdACwzKAA4ctvUxXclrfB7PCZn2sjjhu1RdoSXKuQfwknkM7oL6FCU7/UKSvMZIAA"
    },
    {
      "src": "/stays/jolly-house/27.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAkAA4BaJQBOj+ACm9AckQAA/u0lrcecmUhcmnXGiDHM5n+5VV8bqI82KOmtbnB9vfIg5kWy18zuu/Fu/Nwbd+jMWAAA"
    },
    {
      "src": "/stays/jolly-house/28.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAkAA4BaJYgCdAC8Shc6eAD+9JGRulP0SunMEzMu+Z9391A2Y0o319JRgUpfP3FadQA2aV+Zr0QNo26WxgAA"
    },
    {
      "src": "/stays/jolly-house/29.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQAAkAA4BaJZgCdADDOrP4AAD+0f23S4tKn3zdTGKJe6Bkg1J6yK8UzE/0smw4LEKSbgGsyTAqO93WeFKgMu304IM9piOAF4wjz8CBJeZe68AA"
    },
    {
      "src": "/stays/jolly-house/30.webp",
      "width": 2500,
      "height": 1408,
      "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoQAAkAA4BaJYwCdACNTvEAAPfULFD2e056mqcMwDbe8qu8prbtoyKpDURhqoi3gq3PvYhGf/GYAYAA"
    },
    {
      "src": "/stays/jolly-house/31.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkAA4BaJQBOgB9lc5q34PAAzjVwfi9k3YsDA4iJggaXsdEay/6fiBs2uOFuRgNCq+/OsG78RF8xm3q3GiCdaAAAAA=="
    },
    {
      "src": "/stays/jolly-house/32.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAABQAgCdASoQAAkAA4BaJQBOj+ACzv1Re8koAQAA+uvjGbNbi1Qw1Z0r5SgTf/pzEZmhctFvNHDQGXEW8vAeuvd+8TpRhpipGnW5RDxAAAA="
    },
    {
      "src": "/stays/jolly-house/33.webp",
      "width": 2500,
      "height": 1408,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAQCdASoQAAkAA4BaJQBOgBcIigKAAMq5JrHY+jyW/IR334qY4QF1iZ4ID17U7Ul3iRxqCxyTfkHwm6hcfVvU7i7oarGgAAA="
    },
    {
      "src": "/stays/jolly-house/34.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJbACdADSJtScgAD+g00ODEBB6Q99uG1XuOrtk5YlBkM27fibmjs1y3uOX5tiw73wxW8hjTgtsz+ZIQAAAA=="
    }
  ],
  "light-house": [
    {
      "src": "/stays/light-house/01.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAkAA4BaJQBOgP4Acpdhe4AA/b1NbZ7OG1RuXmPISMMquKwDP7/eEqc9ifXqHg0HUZd2DHvf3imup6b9QRqMURhplyihpAAAAA=="
    },
    {
      "src": "/stays/light-house/02.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoQAAkAA4BaJQBOgMXI0B8TMOxmQAD+j7DPYTLirG3ApSbxp6gVbrXYoBoynq5kWKTRhcSnd66rxZWYGIomc5kc/sSVyLgCP8dbffQc+N5nRwwAAAA="
    },
    {
      "src": "/stays/light-house/03.webp",
      "width": 1900,
      "height": 1070,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAkAA4BaJYwCdAEeXd4sOAAA/KdAXYKqnYGRMX/NZiwhXN/4iqcg2VaukbcXLSkekGDR1/6TFBxzeZNNBMs8UxpLBnMPrsAAAA=="
    },
    {
      "src": "/stays/light-house/04.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJZACdAC9LGRn/gAA/e2KpUR/PjZmqyVawSlLS74DKuBtO2WY95VtqG4MZHXpa/fUU6oOv06tIY2iVaOMHk4ruLu+yj+ozKHGtEAA"
    },
    {
      "src": "/stays/light-house/05.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAkAA4BaJZACdAECujuj5wAA/sAMW09IZybnLcpPtldBjnV2mYkFX6AdsnUPyHX4M28SvobLxOplnj//JnvS3yGV10PS8VVer4AA"
    },
    {
      "src": "/stays/light-house/06.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAQCdASoQAAkAA4BaJQBOgA64ofgA/tvn2ECjudgEiOCFoSYloimvb2jJ4+Sd0FRHpWBO/VFeI+zfwOG1ygZXkqM5h26NQAA="
    },
    {
      "src": "/stays/light-house/07.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoQAAkAA4BaJQBYdhZqgH/AAP7I3L8b4Jhx8+xwG30nkhMyRHRk57pJEbLne29JU54J0bxoCoQZsIAA"
    },
    {
      "src": "/stays/light-house/08.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoQAAkAA4BaJZQAAuPqhZ4dsAD8/1XAfdtdX9JC0zq5hfKWLoeXcX/PUnYs9FqVqdT4YJACIYcAAA=="
    },
    {
      "src": "/stays/light-house/09.webp",
      "width": 3000,
      "height": 1689,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAgCdASoQAAkAA4BaJZACdH8AFVqmUE0IAP4Yj4q0gZbm20vXYTeXbZrOVkc7v8PLTEUeMEa+wwj/ToSlPsFyaHuQAAAA"
    },
    {
      "src": "/stays/light-house/10.webp",
      "width": 900,
      "height": 1599,
      "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JQBOmUABbfj61PJXujh3UQAD+1rY4df7BY5VyvaRJXSxxI8e2Nek5Wo9USuo8y3g+IgYZO6qPnsc1uTwIsafRmrR93XeCfgXSsXfk9uLXEWkebbfMv4kyOrjKz77s7DuurZSGT4FkeYCZwuJVWW3YUlMCItIAAAA="
    },
    {
      "src": "/stays/light-house/11.webp",
      "width": 700,
      "height": 1243,
      "blurDataURL": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAAAwBACdASoQABwAPu1iqU2ppaOiMAgBMB2JZgCdMoAlvxZTNFYJe9UvLoAA+KBLLUUFXIPkwRp2JaIWNLB/0AxNbrnjfSFDv/niaK0TqWPkPZxZ4lEmQWKGwS6kC9RQuKAGFhsOkt1H75JT+9wLL3cRp9dDinDQPObFTMOvcskbActhr0dEooRcpSXqznwTnBl9btld1gguuYV2MdAJ0BmPMvRAAA=="
    },
    {
      "src": "/stays/light-house/12.webp",
      "width": 1900,
      "height": 1070,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAkAA4BaJZACdAEDW+bM1oAA/q+7/M02j6qVKwavyHZjnBeVXTdA+vAGNFuMWxJYEPG5zS7kwZf+QIBNme7hmGmRgQmN2AAAAA=="
    },
    {
      "src": "/stays/light-house/13.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAkAA4BaJQBOgBmAuoh+CAAA+UR6sPWpg857VrXKeuCLE/3pSagDpJlWIQX0bzIjhdfTVTdZptMYqFGvY9xA2J2upEAA"
    },
    {
      "src": "/stays/light-house/14.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAkAA4BaJYgCdAYtpUZLtq6AAPyEPVkfRvuxILmvoC42P/4NS6gf5hCOklao9809Fqna1LsVLiI3m899T788fK/JuJepw9TRNgAA"
    },
    {
      "src": "/stays/light-house/15.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAkAA4BaJQBOgBu1UurMhHwA/tH0gt+P8PnT7WpvHxuHHBM+mURuHxS7dujDRqC3aJd1PKSWAYYKksLw5y8S/YEfpGNsy9ekAAAA"
    },
    {
      "src": "/stays/light-house/16.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAkAA4BaJZACdADpuMlwU8AA/nkaL2CeyPt9UL+aUg0XqXJMSZ0bVEZLRxd6v6RJcyvMLY3900jMi86+FwlFaAfT1ogVry2DeAAA"
    },
    {
      "src": "/stays/light-house/17.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJZgCdADbnkV/AAD4RdQgFhk94weQpcXc8C8O68RFbvEQVJTAkPplid451+dzfXfCbsMOPv9TZc1JpWNAAA=="
    }
  ],
  "snug-studio": [
    {
      "src": "/stays/snug-studio/01.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQAAkAA4BaJZACdADO+A82AADLF4yVxhuNIP2H12y68jNZgoJzWNNv7KWucwlZ7O7MSPzn/2827lDlYrN9SK3+jSv6X+AkiA8TTIUAMmXSNAAA"
    },
    {
      "src": "/stays/snug-studio/02.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJbACdADRAXANAAD9RFY1MHNg7mLfeiJhVW00ldGgrsr6oMXmgLBRzAjok+K6iV1uL8FhgsgVTvzzidcJwLJ4gAA="
    },
    {
      "src": "/stays/snug-studio/03.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABQAgCdASoQAAkAA4BaJYgCdG1/ApFvklV9CEAA/mVaWfzoS3BOP//4aTvnSre8gr5ye/6VKUiM5rkr+KpPQk2FnMRQf0+sE+0c+whzFTpApaFJeXnDhaYAAAA="
    },
    {
      "src": "/stays/snug-studio/04.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJYgCdAEWxK11PAAA/mZaLQXuW7Qm8SUSoED3o2TVgISz3dIdbQ015UJbGnTBTCY8awOwZPoRL816hQC5l4BGdk4xR6av4efkqKAA"
    },
    {
      "src": "/stays/snug-studio/05.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAQCdASoQAAkAA4BaJaACdADdbWLUeggA/md+2AiPav2WWc91fVFW808trNxY9zAitjGCWqCGiKy6bLNfid7kaBryHxeaStFm9hpMxBBQs3fJKIVMgLXIxNhM2IAA"
    },
    {
      "src": "/stays/snug-studio/06.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAkAA4BaJYgCdADPHU5AJYAA/I/P5at5eaofT6/gyplsZeef6vFhPOjW0yIwrJBELQ7VRQQNBE83DsRY6XI8nkSH6od4i6SAAA=="
    },
    {
      "src": "/stays/snug-studio/07.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACQAQCdASoQAAkAA4BaJZgCdABV/+AA/o+RSTebCUgRilbcUnjs0QQiwf89jzizHeM5s6u7R3BfvQbpdUceolmB4ZeKjmbm1hxQNF1NhpOkAaAA"
    },
    {
      "src": "/stays/snug-studio/08.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQAgCdASoQAAkAA4BaJQBOj+AW4A0dLRMfrgAA/eqRVCqeBxsxKOKKmD3a8/Thi61m8kPmltQS7AGu6znHXG4M7pGZ9PdhY83R2VOsNJtdKAHcTiy/C1VE9WAAAA=="
    },
    {
      "src": "/stays/snug-studio/09.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJYwCdAC3BFWPIAD+0dwieWwtdmJswSfEZvy9ebisQ6hciq8ygNm3BxVyEZ7UJIVsl+I7BtepOAc8yQAAAA=="
    },
    {
      "src": "/stays/snug-studio/10.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJYwCdADiGsEz6AD+0dl1UFGhOLF11i10UuUnh2MHGaZMILYgzu5dQBn2/AMuWZzySFoTf07+FQiZ0AAAAA=="
    },
    {
      "src": "/stays/snug-studio/11.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAkAA4BaJYwCdADHs2J64AD+8Xq7tBHpLsWAAL9x5iWBZ2cPVr4t0gZx7d75686bQbiEklEsL8kMTXnkdgAA"
    },
    {
      "src": "/stays/snug-studio/12.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoQAAkAA4BaJZACdAYvXqc7P/CeoAD+jhtUVKQgx2UhuwRJsfZ7qcLF8Qu9UhyPBbtkZ9YRF6lVR7Hj1v9d1QpevPwBR9qXe0d/A3FCLqPa/IWAAAA="
    },
    {
      "src": "/stays/snug-studio/13.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAkAA4BaJbACdAD1bR5CCAAA/cU3ftZJfwkSCNI2ONvrxnq+G6DmXcqWX734x9ZEAEFqflYpF1hrcgt6smqnAwTcNRm9f8N1IAAA"
    },
    {
      "src": "/stays/snug-studio/14.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwAgCdASoQAAkAA4BaJbACdH8AF/2FABGS4AD8i9EWEDIhdh18pFaEdpZEGBlsZ0TbOJKdB0ZenTqf9YT6QdoYQE/nsyvtJCJudPYsiyn5GCN74AAAAA=="
    },
    {
      "src": "/stays/snug-studio/15.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAkAA4BaJagCdACzG/VGmAD11mNwGnpbXsAoS9gCPADNl50wbyE205v6qp7JhYgYMvKJsyXlMZUCTxSRedT2JOhP/+2LEqKPAAAA"
    },
    {
      "src": "/stays/snug-studio/16.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJZgCdADG4Hi6KAD+3RXtHClC/5C7PG0C0czNtwyyZ1lyXK3sptrdnW+T4XBGpilhLIfUr8ip+lXntAAAAA=="
    },
    {
      "src": "/stays/snug-studio/17.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJZQCdADiPPwJdAD+R+ctBSOgwpp8conbn+izTXAhbSufmUSbPWqp3Ez/jZKgX9rao2+FvAg+kOnPuMCbAzoKgAA="
    },
    {
      "src": "/stays/snug-studio/18.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJbACdADs7MraAAD8i4I26kmiVisRZv/586TeqtXXI26VDhqId2zO3ZK5B7Q12GCJ5hsiCeWvGS0XamU2vMK+SIGgAA=="
    },
    {
      "src": "/stays/snug-studio/19.webp",
      "width": 2500,
      "height": 1408,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAkAA4BaJQBOgB4D0bCXgAD+5zZJOQKhWIhbSjXDRcVhdJWq+ggH/vQsaPP9+JUUUQV+6BCahUCxnAA="
    }
  ],
  "wonk-studio": [
    {
      "src": "/stays/wonk-studio/01.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAkAA4BaJbACdADNHD2a2OMAAPkz3J4q2HsIv0GZbCSGbwLRVkaBgQDlh0hEdSVqUjLlUdzcPFc68d2Q3zK2eitnmd0tPGtg9nJstS8/gAAA"
    },
    {
      "src": "/stays/wonk-studio/02.webp",
      "width": 1900,
      "height": 1070,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAkAA4BaJYgCdACztnDnYAAA/GFewaEWLiGz/8NS2ZeTKuWPW6xjDJDgsvkIePgdBiwMa23jC4ol6jFt4wNblbLz0oopAR4AAA=="
    },
    {
      "src": "/stays/wonk-studio/03.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA4BaJZACdAELYKQHwSAA+U3xkQj7gNm4NqjoDe9gMtyDdLx4FVDGHxhmDuUxD1Q8xk0GDYhA54A7lcQxJ1yggRoAAAA="
    },
    {
      "src": "/stays/wonk-studio/04.webp",
      "width": 2095,
      "height": 1179,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAkAA4BaJYgCdAC67gJ70gAA/lYA0X7Hx+wWrNXdU6omlGOr2fU43lJncNi7Z7hw88jRRLOsfTGmRagr6AAA"
    },
    {
      "src": "/stays/wonk-studio/05.webp",
      "width": 1799,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJQBOgB065DW+iAD+0G9eG1ZsorTydkoyHfpe1gKM9DyaZ1FavCpEoVoAx1lnSsWXJEtZNFAzBUiORuhmWO4f2AWAAA=="
    },
    {
      "src": "/stays/wonk-studio/06.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAkAA4BaJaACdAEC0o8yfRAA4k7mfPFZ17WvPW1yb98oUhsBNlJAVMXK5veailWkjcN7wdC16MGhJyVtzMGdBITdgYAA"
    },
    {
      "src": "/stays/wonk-studio/07.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACQAQCdASoQAAkAA4BaJQBOgA0+VgAAzjjTI0VN/KTNLa+LZOoPAdfSNF8sfXsU9Ul721NtQO8mC5tELj7YUmgEEbowhnsfFN7IAA=="
    },
    {
      "src": "/stays/wonk-studio/08.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAkAA4BaJYgCdADD3rjgYxAA/t37UaZ07aMvRtPnoBAV4uxgx3qygKvFDc0TK0PI5witAlo/+/WgpWJnCL6AAAA="
    },
    {
      "src": "/stays/wonk-studio/09.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACwAQCdASoQAAkAA4BaJbACdAC5guxIAPxlvzk+coM5vGdVYUlCXrfbIDOoWYKMDohQ00ffAQPUByvdr5a7kW+GyH16Li8Lq1hL9P4FmqiBI12Z/z2x00WAAAA="
    },
    {
      "src": "/stays/wonk-studio/10.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABQAgCdASoQAAkAA4BaJQBOgMWM5eiK6/TiqQAA9Ac2uNY3bYd4S23dfsmfS7pjZ0tviL4EBLVVJY0Ou7SEXcDwxQpnb+AfOVGyTVdCgeBr2tycAAA="
    },
    {
      "src": "/stays/wonk-studio/11.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAwAgCdASoQAAkAA4BaJYgCdADp9uYmbPFTAAD+5m5uIn3WOeEXXok6LJ5fPeduoMqOKrPDsHJw/LiUanv8GXNEOSE+hufu2izvEAAA"
    },
    {
      "src": "/stays/wonk-studio/12.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoQAAkAA4BaJYwCdAEfq/TaKuGGAAD9wv1Z7ANX3Cr4MktESjeCVpy5BdwI0tOipuFKmD2FkE3tffhSJYxIfcXqlS2jOYTpVyqI4cwiBAA="
    },
    {
      "src": "/stays/wonk-studio/13.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAkAA4BaJZwAAve/SrfvY/AA/t4MkkwMmJEGhbsPQo/gvGjEVN7BG3iItbha5D1bqoLvEEuSv4AA"
    },
    {
      "src": "/stays/wonk-studio/14.webp",
      "width": 1600,
      "height": 901,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJagCdAEG9wa0wAD44w1EswzOSnInQtv6suv5MkACqFPXWgtuo6KLO8B6RqHLfGnv8CKUTMzbGgmO5JAAAA=="
    },
    {
      "src": "/stays/wonk-studio/15.webp",
      "width": 2500,
      "height": 1408,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAkAA4BaJZgCdADdGiSeU8AA/gllEX3mXZm7SVJOF/GyTmSL6/Zab4dZ4WU/RIsCXXeJYWqek1c0Da+nP0PXVp6B7sGcDe2ikkoAAAA="
    },
    {
      "src": "/stays/wonk-studio/16.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkAA4BaJQBOgB9fvDk+7jAA/js3A+xFeiKe82ckjosjF6xDf1unGnFayZkPCQyGQWfAn7EWazB+q4AUrkBvZGfAAA=="
    },
    {
      "src": "/stays/wonk-studio/17.webp",
      "width": 1800,
      "height": 1013,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA4BaJaACdADMqYvQDQAA+OFlha4Ior5fiPvFbcdFomNw572JjLH0DX0KnY4i2QwGaXoQccIAcPDX5/BugWfAOMsAAAA="
    },
    {
      "src": "/stays/wonk-studio/18.webp",
      "width": 2501,
      "height": 1408,
      "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoQAAkAA4BaJQBdgBM4BnQAAP7Td9o8M+A/PIemOHhzCp5hlSD6PWdE2/kJai4kLbDrizLECS57uAAA"
    }
  ]
};
